<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_f4iDEB4XEfG_jsm1Ob_k5A" name="MyDiagram" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_f4iqIB4XEfG_jsm1Ob_k5A" name="Atendimento Clínica Olho">
      <elements xmi:type="process:Lane" xmi:id="_f4iqIR4XEfG_jsm1Ob_k5A" name="Recepcionista" actor="_QyYG0FPOEfG9dLD7G3QBDg">
        <elements xmi:type="process:StartEvent" xmi:id="_f4iqIh4XEfG_jsm1Ob_k5A" name="Iniciar1" outgoing="_bh6rUFPREfG9dLD7G3QBDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f4iqIx4XEfG_jsm1Ob_k5A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f4iqJB4XEfG_jsm1Ob_k5A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f4iqJR4XEfG_jsm1Ob_k5A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_M-r18FPSEfG9dLD7G3QBDg" name="G00 - gateway padrão" outgoing="_R1S_kFPSEfG9dLD7G3QBDg" incoming="_Gh28cFPSEfG9dLD7G3QBDg _IfUHoFPSEfG9dLD7G3QBDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GhkBgFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GhizYFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GhkokFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_gAK38FPUEfG9dLD7G3QBDg" name="possui cadastro?" outgoing="_rjkxEFPREfG9dLD7G3QBDg _9BqYkFPREfG9dLD7G3QBDg" incoming="_bh6rUFPREfG9dLD7G3QBDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bhMSkFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bhLEcFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bhM5oFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_xvtb0FPUEfG9dLD7G3QBDg" name="forma de pagamento?" outgoing="_ZoTo4FPSEfG9dLD7G3QBDg _tDF7sFPUEfG9dLD7G3QBDg" incoming="_R1S_kFPSEfG9dLD7G3QBDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_R1AEoVPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_R1AEoFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_R1AEolPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_zt3xoFPUEfG9dLD7G3QBDg" name="G20 - gateway padrão" outgoing="_EAUfwFfjEfGaAKjg7KE34A" incoming="_tDF7sFPUEfG9dLD7G3QBDg _KYOXkG6NEfGFG66_bEuG_g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_R2fngVPUEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_R2fngFPUEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_R2fnglPUEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_6SE50FfXEfGaAKjg7KE34A" documentation="o serviço está agendado?" name="agendado?" outgoing="_Kz_L8FfjEfGaAKjg7KE34A _Oxlp8FfjEfGaAKjg7KE34A" incoming="_EAUfwFfjEfGaAKjg7KE34A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6SJLQFfXEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6SIkMFfXEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6SJLQVfXEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_X5NSIF-sEfGJm-VfRlIdsQ" name="End1" incoming="_X5yg8F-sEfGJm-VfRlIdsQ _Gj-p4G6NEfGFG66_bEuG_g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_X5SKoF-sEfGJm-VfRlIdsQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_X5RjkF-sEfGJm-VfRlIdsQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_X5SKoV-sEfGJm-VfRlIdsQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_dCIDsGOREfGaD418Sxm7uA" name="tipo de serviço?" outgoing="_lmwD0FfjEfGaAKjg7KE34A _0w-LQFfjEfGaAKjg7KE34A _5yIWQGOPEfGaD418Sxm7uA" incoming="_Kz_L8FfjEfGaAKjg7KE34A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KzuGMVfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KzuGMFfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KzuGMlfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ec3jYGOREfGaD418Sxm7uA" name="exame ou procedimento?" outgoing="_A7AfMFfkEfGaAKjg7KE34A _lPn7gGOPEfGaD418Sxm7uA" incoming="_0w-LQFfjEfGaAKjg7KE34A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0wvhwVfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0wvhwFfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0wvhwlfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_gqhGsGOREfGaD418Sxm7uA" name="G30 - gateway padrão" outgoing="_bxCPQGOREfGaD418Sxm7uA" incoming="_PXjxIGOREfGaD418Sxm7uA _aLIzAGOSEfGaD418Sxm7uA _by5bAGOSEfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PXF3EWOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PXF3EGOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PXGeIGOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ofCy8GOREfGaD418Sxm7uA" name="precisa realizar outro serviço?" outgoing="_sAv_IGOREfGaD418Sxm7uA _BcUI0GOSEfGaD418Sxm7uA" incoming="_bxCPQGOREfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bwv7YGOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bwvUUGOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bwv7YWOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_sAeSUGOREfGaD418Sxm7uA" name="End3" incoming="_sAv_IGOREfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sAhVoWOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sAhVoGOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sAhVomOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_B47zYGOSEfGaD418Sxm7uA" name="lente de contato?" outgoing="_HBoLgGOSEfGaD418Sxm7uA _i0choHJ5EfGBPZMgfyOTVw" incoming="_BcUI0GOSEfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BcOpQWOSEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BcOpQGOSEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BcOpQmOSEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_JGETAGOTEfGaD418Sxm7uA" name="T10 - Cadastrar paciente" outgoing="_Gh28cFPSEfG9dLD7G3QBDg" incoming="_9BqYkFPREfG9dLD7G3QBDg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9BR-EVPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9BR-EFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9BR-ElPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_rFK7UHJxEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rFK7UXJxEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rFK7UnJxEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rFK7U3JxEfGBPZMgfyOTVw" name="atendimentoInput.nomePaciente" content="atendimentoInput?.nomePaciente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rFK7VHJxEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rFK7VXJxEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setNomePaciente">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_rFK7VnJxEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rFK7V3JxEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rFK7WHJxEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rFK7WXJxEfGBPZMgfyOTVw" name="atendimentoInput.cpfPaciente" content="atendimentoInput?.cpfPaciente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rFK7WnJxEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rFK7W3JxEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setCpfPaciente">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_rFK7XHJxEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rFK7XXJxEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rFK7XnJxEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rFK7X3JxEfGBPZMgfyOTVw" name="atendimentoInput.telefonePaciente" content="atendimentoInput?.telefonePaciente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rFK7YHJxEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rFK7YXJxEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setTelefonePaciente">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_rFK7YnJxEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rFK7Y3JxEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rFK7ZHJxEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rFK7ZXJxEfGBPZMgfyOTVw" name="atendimentoInput.formaPagamento" content="atendimentoInput?.formaPagamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rFK7ZnJxEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rFK7Z3JxEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setFormaPagamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_rFK7aHJxEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rFK7aXJxEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rFK7anJxEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rFK7a3JxEfGBPZMgfyOTVw" name="atendimentoInput.agendado" content="atendimentoInput?.agendado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rFK7bHJxEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rFK7bXJxEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setAgendado">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_rFK7bnJxEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rFK7b3JxEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rFK7cHJxEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rFK7cXJxEfGBPZMgfyOTVw" name="atendimentoInput.tipoServico" content="atendimentoInput?.tipoServico" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rFK7cnJxEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rFK7c3JxEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setTipoServico">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_rFK7dHJxEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_rFK7dXJxEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_rFK7dnJxEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_rFK7d3JxEfGBPZMgfyOTVw" name="atendimentoInput.exameOuProcedimento" content="atendimentoInput?.exameOuProcedimento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_rFK7eHJxEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_rFK7eXJxEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setExameOuProcedimento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9BR-E1PREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9BR-FFPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9BR-FVPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9BR-F1PREfG9dLD7G3QBDg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9BR-FlPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_JGGIOGOTEfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_q3rVAHM5EfGeM5ggmLUPBQ" name="cadastrarPaciente" content="eafe24f3-0da3-4768-bf6f-a53ef717f2bb" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_JGGIN2OTEfGaD418Sxm7uA">
            <inputs xmi:type="process:ContractInput" xmi:id="_rFKUQHJxEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_rFKUQXJxEfGBPZMgfyOTVw" name="nomePaciente" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_rFKUQnJxEfGBPZMgfyOTVw" name="cpfPaciente" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_rFKUQ3JxEfGBPZMgfyOTVw" name="telefonePaciente" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_rFKURHJxEfGBPZMgfyOTVw" name="formaPagamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_rFKURXJxEfGBPZMgfyOTVw" name="agendado" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_rFKURnJxEfGBPZMgfyOTVw" name="tipoServico" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_rFKUR3JxEfGBPZMgfyOTVw" name="exameOuProcedimento" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_JGGIOmOTEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5MLHYGUtEfGEXrYvpS-i_A" documentation="Verifica com o paciente se os dados que estão na ficha de cadastro dele estão corretos. Caso não estejam, são atualizados com os dados fornecidos pelo paciente." name="T00 - Confirmar ou atualizar cadastro" outgoing="_IfUHoFPSEfG9dLD7G3QBDg" incoming="_rjkxEFPREfG9dLD7G3QBDg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rjKhYFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rjJ6UFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rjKhYVPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_HIusuHJyEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_HIusuXJyEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HIusunJyEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_HIusu3JyEfGBPZMgfyOTVw" name="atendimentoInput.nomePaciente" content="atendimentoInput?.nomePaciente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_HIusvHJyEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_HIusvXJyEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setNomePaciente">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_HIusvnJyEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_HIusv3JyEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HIuswHJyEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_HIuswXJyEfGBPZMgfyOTVw" name="atendimentoInput.cpfPaciente" content="atendimentoInput?.cpfPaciente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_HIuswnJyEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_HIusw3JyEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setCpfPaciente">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_HIusxHJyEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_HIusxXJyEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HIusxnJyEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_HIusx3JyEfGBPZMgfyOTVw" name="atendimentoInput.telefonePaciente" content="atendimentoInput?.telefonePaciente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_HIusyHJyEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_HIusyXJyEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setTelefonePaciente">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_HIusynJyEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_HIusy3JyEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HIuszHJyEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_HIuszXJyEfGBPZMgfyOTVw" name="atendimentoInput.formaPagamento" content="atendimentoInput?.formaPagamento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_HIusznJyEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_HIusz3JyEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setFormaPagamento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_HIus0HJyEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_HIus0XJyEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HIus0nJyEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_HIus03JyEfGBPZMgfyOTVw" name="atendimentoInput.agendado" content="atendimentoInput?.agendado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_HIus1HJyEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_HIus1XJyEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setAgendado">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_HIus1nJyEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_HIus13JyEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HIus2HJyEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_HIus2XJyEfGBPZMgfyOTVw" name="atendimentoInput.tipoServico" content="atendimentoInput?.tipoServico" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_HIus2nJyEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_HIus23JyEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setTipoServico">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_HIus3HJyEfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_HIus3XJyEfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_HIus3nJyEfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_HIus33JyEfGBPZMgfyOTVw" name="atendimentoInput.exameOuProcedimento" content="atendimentoInput?.exameOuProcedimento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_HIus4HJyEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_HIus4XJyEfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setExameOuProcedimento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rjKhYlPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rjKhY1PREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rjKhZFPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rjKhZlPREfG9dLD7G3QBDg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rjKhZVPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5MM8mWUtEfGEXrYvpS-i_A">
            <targetForm xmi:type="expression:Expression" xmi:id="_XROS0HM5EfGeM5ggmLUPBQ" name="atualizarCadastro" content="df528874-8026-4fd1-970c-b20143bb0c0f" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5MM8mGUtEfGEXrYvpS-i_A">
            <inputs xmi:type="process:ContractInput" xmi:id="_HIussHJyEfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_HIussXJyEfGBPZMgfyOTVw" name="nomePaciente" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_HIussnJyEfGBPZMgfyOTVw" name="cpfPaciente" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_HIuss3JyEfGBPZMgfyOTVw" name="telefonePaciente" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_HIustHJyEfGBPZMgfyOTVw" name="formaPagamento" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_HIustXJyEfGBPZMgfyOTVw" name="agendado" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_HIustnJyEfGBPZMgfyOTVw" name="tipoServico" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_HIust3JyEfGBPZMgfyOTVw" name="exameOuProcedimento" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5MM8m2UtEfGEXrYvpS-i_A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_topqYGnOEfGG3LJZ6zip9w" name="T30 - Agendar serviço" outgoing="_X5yg8F-sEfGJm-VfRlIdsQ" incoming="_Oxlp8FfjEfGaAKjg7KE34A _i0choHJ5EfGBPZMgfyOTVw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_torfkWnOEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_torfkGnOEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_torfkmnOEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_torflWnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_torflmnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_torfl2nOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_torfmWnOEfGG3LJZ6zip9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_torfmGnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <inputMappings xmi:type="process:InputMapping" xmi:id="_wvkyQG9kEfGtvrE_zk-BVg" subprocessTarget="atendimentoInput">
            <processSource xmi:type="expression:Expression" xmi:id="_wvlZUG9kEfGtvrE_zk-BVg" name="mapAtendimentoInput" content="[horarioEscolhido: atendimento?.horarioEscolhido, profissionalEspecifico: atendimento?.profissionalEspecifico, profissionalSolicitado: atendimento?.profissionalSolicitado]" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Map">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Tqe18G9lEfGtvrE_zk-BVg" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </processSource>
          </inputMappings>
          <outputMappings xmi:type="process:OutputMapping" xmi:id="_PhFv8G9rEfGtvrE_zk-BVg" subprocessSource="atendimento" processTarget="_GzGOIG5EEfGX2cXNLLb0FA"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_tot70GnOEfGG3LJZ6zip9w" name="Agendar serviço" content="Agendar serviço" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_torflGnOEfGG3LJZ6zip9w" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_pVEEgGquEfGJ4sykcPaQUw" name="T20 - Autorizar serviço com operadora de saúde" outgoing="_8dN1QG6MEfGFG66_bEuG_g" incoming="_ZoTo4FPSEfG9dLD7G3QBDg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zn4LEFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zn3kAFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zn4yIFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_doqRAG6OEfGFG66_bEuG_g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_doqRAW6OEfGFG66_bEuG_g" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_doqRAm6OEfGFG66_bEuG_g" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_doqRA26OEfGFG66_bEuG_g" name="atendimentoInput.servicoAutorizadoPlano" content="return atendimentoInput.servicoAutorizadoPlano" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mBxqQHG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_doqRBW6OEfGFG66_bEuG_g" type="JAVA_METHOD" expression="setServicoAutorizadoPlano">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_doqRBm6OEfGFG66_bEuG_g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_doqRB26OEfGFG66_bEuG_g" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_doqRCG6OEfGFG66_bEuG_g" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_doqRCW6OEfGFG66_bEuG_g" name="atendimentoInput.senhaAutorizacao" content="return atendimentoInput.senhaAutorizacao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_nSYWgHG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_doqRC26OEfGFG66_bEuG_g" type="JAVA_METHOD" expression="setSenhaAutorizacao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_doqRDG6OEfGFG66_bEuG_g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_doqRDW6OEfGFG66_bEuG_g" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_doqRDm6OEfGFG66_bEuG_g" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_doqRD26OEfGFG66_bEuG_g" name="atendimentoInput.observacoesAutorizacao" content="return atendimentoInput.observacoesAutorizacao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_oMMTYHG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_doqREW6OEfGFG66_bEuG_g" type="JAVA_METHOD" expression="setObservacoesAutorizacao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zn4yIVPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zn4yIlPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zn4yI1PSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zn4yJVPSEfG9dLD7G3QBDg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zn4yJFPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pVFSqWquEfGJ4sykcPaQUw">
            <targetForm xmi:type="expression:Expression" xmi:id="_1YclEHM5EfGeM5ggmLUPBQ" name="autorizarComPlano" content="6c29a774-80b3-4543-a87d-046f22058249" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pVFSqGquEfGJ4sykcPaQUw">
            <inputs xmi:type="process:ContractInput" xmi:id="_JKKU0HG1EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_JKKU0nG1EfGBPZMgfyOTVw" name="servicoAutorizadoPlano" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JKKU03G1EfGBPZMgfyOTVw" name="senhaAutorizacao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JKKU1HG1EfGBPZMgfyOTVw" name="observacoesAutorizacao" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_pVFSq2quEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_9DP6gG6MEfGFG66_bEuG_g" name="serviço autorizado?" outgoing="_Gj-p4G6NEfGFG66_bEuG_g _KYOXkG6NEfGFG66_bEuG_g" incoming="_8dN1QG6MEfGFG66_bEuG_g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8cWSkW6MEfGFG66_bEuG_g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8cWSkG6MEfGFG66_bEuG_g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8cWSkm6MEfGFG66_bEuG_g" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_k2ts8B4aEfG2S7DpaDzKGg" name="Médico(a)" actor="_xFzCwGRUEfG-37a2zyZkMg">
        <elements xmi:type="process:Task" xmi:id="_ULXJQGOPEfGaD418Sxm7uA" name="T60 - Registrar informações obtidas no procedimento" outgoing="_PXjxIGOREfGaD418Sxm7uA" incoming="_A7AfMFfkEfGaAKjg7KE34A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A6wAgVfkEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A6wAgFfkEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A6wAglfkEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_s67ssHG5EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s67ssXG5EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s67ssnG5EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s67ss3G5EfGBPZMgfyOTVw" name="atendimentoInput.precisaOutroServico" content="return atendimentoInput.precisaOutroServico" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_tuuH0HG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s67stXG5EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setPrecisaOutroServico">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_s67stnG5EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_s67st3G5EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_s67suHG5EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_s67suXG5EfGBPZMgfyOTVw" name="atendimentoInput.informacoesProcedimento" content="return atendimentoInput.informacoesProcedimento" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_uiJI0HG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_s67su3G5EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setInformacoesProcedimento">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_KV3ENnG7EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_KV3EN3G7EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KV3EOHG7EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_KV3EOXG7EfGBPZMgfyOTVw" name="atendimentoInput.lenteContato" content="atendimentoInput?.lenteContato" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_voBLwHG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_KV3EO3G7EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setLenteContato">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_A6wAg1fkEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_A6wAhFfkEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_A6wAhVfkEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_A6wAh1fkEfGaAKjg7KE34A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_A6wAhlfkEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ULnA52OPEfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_YGNkoHM6EfGeM5ggmLUPBQ" name="formProcedimento" content="059c5c8f-f8e4-4b45-a47e-36b419d91f8e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ULnA5mOPEfGaD418Sxm7uA">
            <inputs xmi:type="process:ContractInput" xmi:id="_KVzZ0HG7EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_KV0A4HG7EfGBPZMgfyOTVw" name="precisaOutroServico" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_KV0A4XG7EfGBPZMgfyOTVw" name="lenteContato" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_KV0A4nG7EfGBPZMgfyOTVw" name="informacoesProcedimento" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ULnn8GOPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Jwk6gGOREfGaD418Sxm7uA" name="T50 - Registrar informações obtidas na consulta" outgoing="_by5bAGOSEfGaD418Sxm7uA" incoming="_gWRKcGOQEfGaD418Sxm7uA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gWDvEWOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gWDvEGOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gWDvEmOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_2Lxl83G5EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2Lxl9HG5EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2Lxl9XG5EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2Lxl9nG5EfGBPZMgfyOTVw" name="atendimentoInput.precisaOutroServico" content="return atendimentoInput.precisaOutroServico" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_xobkUHG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2Lxl-HG5EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setPrecisaOutroServico">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_2Lxl-XG5EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_2Lxl-nG5EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_2Lxl-3G5EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_2Lxl_HG5EfGBPZMgfyOTVw" name="atendimentoInput.informacoesConsulta" content="return atendimentoInput.informacoesConsulta" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yfgWQHG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_2Lxl_nG5EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setInformacoesConsulta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_lIrmdnG7EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_lIrmd3G7EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_lIrmeHG7EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_lIrmeXG7EfGBPZMgfyOTVw" name="atendimentoInput.lenteContato" content="atendimentoInput?.lenteContato" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_zCix4HG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_lIrme3G7EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setLenteContato">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_gWDvE2OQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_gWDvFGOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_gWDvFWOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_gWDvF2OQEfGaD418Sxm7uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_gWDvFmOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_JwmvuWOREfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_OVAwUHM6EfGeM5ggmLUPBQ" name="formConsulta" content="d3c91229-8402-41c5-85b7-33badca3f07d" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_JwmvuGOREfGaD418Sxm7uA">
            <inputs xmi:type="process:ContractInput" xmi:id="_lIq_YHG7EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_lIq_YXG7EfGBPZMgfyOTVw" name="precisaOutroServico" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_lIq_YnG7EfGBPZMgfyOTVw" name="lenteContato" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_lIq_Y3G7EfGBPZMgfyOTVw" name="informacoesConsulta" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Jwmvu2OREfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_lLRnsB4aEfG2S7DpaDzKGg" name="Equipe pré-consulta" actor="_5TtksGUrEfGEXrYvpS-i_A">
        <elements xmi:type="process:Task" xmi:id="_3IDTwF-sEfGJm-VfRlIdsQ" name="T40 - Registrar informações obtidas na pré-consulta" outgoing="_gWRKcGOQEfGaD418Sxm7uA" incoming="_lmwD0FfjEfGaAKjg7KE34A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lmp9MlfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lmp9MVfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lmp9M1fjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Vq77gXG6EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vq77gnG6EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vq77g3G6EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vq77hHG6EfGBPZMgfyOTVw" name="atendimentoInput.informacoesPreConsulta" content="atendimentoInput?.informacoesPreConsulta" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vq77hXG6EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vq77hnG6EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setInformacoesPreConsulta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lmp9NFfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lmp9NVfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lmp9NlfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lmp9OFfjEfGaAKjg7KE34A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lmp9N1fjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_3IJaZl-sEfGJm-VfRlIdsQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_HYEMUHM6EfGeM5ggmLUPBQ" name="formPreConsulta" content="09e7b847-9cc4-4a1a-9016-2f940facc03d" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_3IJaZV-sEfGJm-VfRlIdsQ">
            <inputs xmi:type="process:ContractInput" xmi:id="_Vq7UcHG6EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_Vq77gHG6EfGBPZMgfyOTVw" name="informacoesPreConsulta" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_3IKBcF-sEfGJm-VfRlIdsQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_KkU7sF-sEfGJm-VfRlIdsQ" name="Técnico(a) de saúde" actor="_819jcGUrEfGEXrYvpS-i_A">
        <elements xmi:type="process:Task" xmi:id="_KOY34GOREfGaD418Sxm7uA" name="T70 - Registrar informações obtidas no exame" outgoing="_aLIzAGOSEfGaD418Sxm7uA" incoming="_lPn7gGOPEfGaD418Sxm7uA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lPTycGOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lPTLYGOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lPTycWOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_on-0UHG6EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_on-0UXG6EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_on-0UnG6EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_on-0U3G6EfGBPZMgfyOTVw" name="atendimentoInput.precisaOutroServico" content="return atendimentoInput.precisaOutroServico" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_1VBx4HG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_on-0VXG6EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setPrecisaOutroServico">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_on-0VnG6EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_on-0V3G6EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_on-0WHG6EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_on-0WXG6EfGBPZMgfyOTVw" name="atendimentoInput.informacoesExame" content="return atendimentoInput.informacoesExame" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2IiScHG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_on-0W3G6EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setInformacoesExame">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_GbnmxnG8EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Gbnmx3G8EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_GbnmyHG8EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_GbnmyXG8EfGBPZMgfyOTVw" name="atendimentoInput.lenteContato" content="atendimentoInput?.lenteContato" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_2jGukHG-EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Gbnmy3G8EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setLenteContato">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lPTycmOPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lPTyc2OPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lPTydGOPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lPTydmOPEfGaD418Sxm7uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lPTydWOPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_KOeXeGOREfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_jW0WMHM6EfGeM5ggmLUPBQ" name="formExame" content="4362bf57-fa58-47f8-81b3-6e98230876e1" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_KOeXd2OREfGaD418Sxm7uA">
            <inputs xmi:type="process:ContractInput" xmi:id="_Gbm_sHG8EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_Gbm_sXG8EfGBPZMgfyOTVw" name="precisaOutroServico" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Gbm_snG8EfGBPZMgfyOTVw" name="lenteContato" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Gbm_s3G8EfGBPZMgfyOTVw" name="informacoesExame" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_KOeXemOREfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_kFheAF-sEfGJm-VfRlIdsQ" name="Venda de lentes" actor="_JTFLcGUsEfGEXrYvpS-i_A">
        <elements xmi:type="process:EndEvent" xmi:id="_YkOxgGOQEfGaD418Sxm7uA" name="End2" incoming="_Yk-_cGOQEfGaD418Sxm7uA _aMnEkGOQEfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YkWGQWOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YkWGQGOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YkWGQmOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_eZxokGOQEfGaD418Sxm7uA" name="possui guia?" outgoing="_VEwZ8GOQEfGaD418Sxm7uA _aMnEkGOQEfGaD418Sxm7uA" incoming="_WcnlMHG8EfGBPZMgfyOTVw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5xv7wGOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5xvUsGOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5xv7wWOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_NLOxkGOTEfGaD418Sxm7uA" name="T85 - Realizar venda de lentes" outgoing="_Yk-_cGOQEfGaD418Sxm7uA" incoming="_VEwZ8GOQEfGaD418Sxm7uA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VEWxUGOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VEVjMGOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VEWxUWOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_6FGuMnNJEfGeM5ggmLUPBQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_6FGuM3NJEfGeM5ggmLUPBQ" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_6FGuNHNJEfGeM5ggmLUPBQ" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_6FGuNXNJEfGeM5ggmLUPBQ" name="atendimentoInput.dataCompraLente" content="atendimentoInput?.dataCompraLente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_6FGuNnNJEfGeM5ggmLUPBQ" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_6FGuN3NJEfGeM5ggmLUPBQ" type="JAVA_METHOD" expression="setDataCompraLente">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VEWxUmOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VEWxU2OQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VEWxVGOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VEWxVmOQEfGaD418Sxm7uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VEWxVWOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_NLP_uWOTEfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_7o1KwHNJEfGeM5ggmLUPBQ" name="formVendaLente" content="84092e47-e364-4e59-bbb3-ae020a6213ce" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_NLP_uGOTEfGaD418Sxm7uA">
            <inputs xmi:type="process:ContractInput" xmi:id="_6FGuMHNJEfGeM5ggmLUPBQ" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_6FGuMXNJEfGeM5ggmLUPBQ" name="dataCompraLente" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_NLQmwGOTEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_QG7OcHG8EfGBPZMgfyOTVw" name="T80 - Solicitar apresentação da guia" outgoing="_WcnlMHG8EfGBPZMgfyOTVw" incoming="_5yIWQGOPEfGaD418Sxm7uA _HBoLgGOSEfGaD418Sxm7uA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QG_f4XG8EfGBPZMgfyOTVw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QG_f4HG8EfGBPZMgfyOTVw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QG_f4nG8EfGBPZMgfyOTVw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_ZO1OInG8EfGBPZMgfyOTVw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ZO1OI3G8EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ZO1OJHG8EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ZO1OJXG8EfGBPZMgfyOTVw" name="atendimentoInput.possuiGuia" content="atendimentoInput?.possuiGuia" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ZO1OJnG8EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ZO1OJ3G8EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setPossuiGuia">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QG_f43G8EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QG_f5HG8EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QG_f5XG8EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QHAG8HG8EfGBPZMgfyOTVw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QG_f5nG8EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QHAG8nG8EfGBPZMgfyOTVw">
            <targetForm xmi:type="expression:Expression" xmi:id="_rjdngHM6EfGeM5ggmLUPBQ" name="formPossuiGuia" content="79bc9f20-f24e-4da3-922c-22f334d20682" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QHAG8XG8EfGBPZMgfyOTVw">
            <inputs xmi:type="process:ContractInput" xmi:id="_ZO1OIHG8EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_ZO1OIXG8EfGBPZMgfyOTVw" name="possuiGuia" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QHAG9HG8EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_GzGOIG5EEfGX2cXNLLb0FA" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico">
        <defaultValue xmi:type="expression:Expression" xmi:id="_uN_FgG6DEfGFG66_bEuG_g" name="initAtendimento()" content="def atendimentoOftalmologicoVar = new clinicaOlho.model.AtendimentoOftalmologico()&#xA;atendimentoOftalmologicoVar.possuiCadastro = atendimentoInput?.possuiCadastro&#xA;return atendimentoOftalmologicoVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="clinicaOlho.model.AtendimentoOftalmologico">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_uOAToG6DEfGFG66_bEuG_g" name="atendimentoInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_f4iqMx4XEfG_jsm1Ob_k5A">
        <targetForm xmi:type="expression:Expression" xmi:id="_PblzUHM5EfGeM5ggmLUPBQ" name="formInicial" content="214f4e85-3ecd-4187-ac36-101e512bb228" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_f4iqNR4XEfG_jsm1Ob_k5A">
        <targetForm xmi:type="expression:Expression" xmi:id="_f4iqNh4XEfG_jsm1Ob_k5A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bh6rUFPREfG9dLD7G3QBDg" target="_gAK38FPUEfG9dLD7G3QBDg" source="_f4iqIh4XEfG_jsm1Ob_k5A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bh9HkFPREfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_bh9HkVPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rjkxEFPREfG9dLD7G3QBDg" name="sim" target="_5MLHYGUtEfGEXrYvpS-i_A" source="_gAK38FPUEfG9dLD7G3QBDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rjlYIFPREfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_rjlYIVPREfG9dLD7G3QBDg" name="possuiCadastroSim" content="return Boolean.TRUE.equals(atendimento.possuiCadastro)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_KVkl0G6FEfGFG66_bEuG_g" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9BqYkFPREfG9dLD7G3QBDg" name="não" target="_JGETAGOTEfGaD418Sxm7uA" source="_gAK38FPUEfG9dLD7G3QBDg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9BrmsFPREfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_9BsNwFPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Gh28cFPSEfG9dLD7G3QBDg" target="_M-r18FPSEfG9dLD7G3QBDg" source="_JGETAGOTEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Gh3jgFPSEfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Gh3jgVPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IfUHoFPSEfG9dLD7G3QBDg" target="_M-r18FPSEfG9dLD7G3QBDg" source="_5MLHYGUtEfGEXrYvpS-i_A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IfVVwFPSEfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IfWj4FPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_R1S_kFPSEfG9dLD7G3QBDg" target="_xvtb0FPUEfG9dLD7G3QBDg" source="_M-r18FPSEfG9dLD7G3QBDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_R1S_kVPSEfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_R1TmoFPSEfG9dLD7G3QBDg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZoTo4FPSEfG9dLD7G3QBDg" name="plano" target="_pVEEgGquEfGJ4sykcPaQUw" source="_xvtb0FPUEfG9dLD7G3QBDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZoUP8FPSEfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZoU3AFPSEfG9dLD7G3QBDg" name="formaPagamentoPlano" content="return &quot;plano&quot;.equals(atendimento.formaPagamento)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_S3ifcHG9EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tDF7sFPUEfG9dLD7G3QBDg" name="particular" target="_zt3xoFPUEfG9dLD7G3QBDg" source="_xvtb0FPUEfG9dLD7G3QBDg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tDHw4FPUEfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_tDHw4VPUEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EAUfwFfjEfGaAKjg7KE34A" target="_6SE50FfXEfGaAKjg7KE34A" source="_zt3xoFPUEfG9dLD7G3QBDg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EAYKIFfjEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_EAYKIVfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Kz_L8FfjEfGaAKjg7KE34A" name="sim" target="_dCIDsGOREfGaD418Sxm7uA" source="_6SE50FfXEfGaAKjg7KE34A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Kz_L8VfjEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Kz_L8lfjEfGaAKjg7KE34A" name="pacienteAgendadoSim" content="return Boolean.TRUE.equals(atendimento.agendado)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_G8bh8G6UEfGFG66_bEuG_g" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Oxlp8FfjEfGaAKjg7KE34A" name="não" target="_topqYGnOEfGG3LJZ6zip9w" source="_6SE50FfXEfGaAKjg7KE34A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OxoGMFfjEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_OxotQFfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lmwD0FfjEfGaAKjg7KE34A" name="consulta" target="_3IDTwF-sEfGJm-VfRlIdsQ" source="_dCIDsGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lmwD0VfjEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_lmwD0lfjEfGaAKjg7KE34A" name="tipoConsultaRetorno" content="return &quot;consulta&quot;.equals(atendimento.tipoServico)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_0GaRQHNAEfGeM5ggmLUPBQ" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0w-LQFfjEfGaAKjg7KE34A" name="exame/procedimento" target="_ec3jYGOREfGaD418Sxm7uA" source="_dCIDsGOREfGaD418Sxm7uA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0w-LQVfjEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_0w-LQlfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_A7AfMFfkEfGaAKjg7KE34A" name="procedimento" target="_ULXJQGOPEfGaD418Sxm7uA" source="_ec3jYGOREfGaD418Sxm7uA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_A7BGQFfkEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_A7BGQVfkEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_X5yg8F-sEfGJm-VfRlIdsQ" target="_X5NSIF-sEfGJm-VfRlIdsQ" source="_topqYGnOEfGG3LJZ6zip9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_X5zIAF-sEfGJm-VfRlIdsQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_X5zIAV-sEfGJm-VfRlIdsQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lPn7gGOPEfGaD418Sxm7uA" name="exame" target="_KOY34GOREfGaD418Sxm7uA" source="_ec3jYGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lPoikGOPEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_lPoikWOPEfGaD418Sxm7uA" name="ehExame" content="return &quot;exame&quot;.equals(atendimento.exameOuProcedimento)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_refExameProcD418Sxm7uA" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5yIWQGOPEfGaD418Sxm7uA" name="venda de lente" target="_QG7OcHG8EfGBPZMgfyOTVw" source="_dCIDsGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5yI9UGOPEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_5yJkYGOPEfGaD418Sxm7uA" name="tipoVendaLente" content="return &quot;venda de lente&quot;.equals(atendimento.tipoServico)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_refTipoVendaLntD418Sxm7uA" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VEwZ8GOQEfGaD418Sxm7uA" name="sim" target="_NLOxkGOTEfGaD418Sxm7uA" source="_eZxokGOQEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VEyPIGOQEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_VEyPIWOQEfGaD418Sxm7uA" name="possuiGuiaSim" content="return Boolean.TRUE.equals(atendimento.possuiGuia)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_refPossuiGuiaD418Sxm7uA" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Yk-_cGOQEfGaD418Sxm7uA" target="_YkOxgGOQEfGaD418Sxm7uA" source="_NLOxkGOTEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Yk-_cWOQEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Yk_mgGOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aMnEkGOQEfGaD418Sxm7uA" name="não" target="_YkOxgGOQEfGaD418Sxm7uA" source="_eZxokGOQEfGaD418Sxm7uA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aMnroGOQEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_aMnroWOQEfGaD418Sxm7uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gWRKcGOQEfGaD418Sxm7uA" target="_Jwk6gGOREfGaD418Sxm7uA" source="_3IDTwF-sEfGJm-VfRlIdsQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gWRxgGOQEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_gWRxgWOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PXjxIGOREfGaD418Sxm7uA" target="_gqhGsGOREfGaD418Sxm7uA" source="_ULXJQGOPEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PXkYMGOREfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_PXkYMWOREfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bxCPQGOREfGaD418Sxm7uA" target="_ofCy8GOREfGaD418Sxm7uA" source="_gqhGsGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bxCPQWOREfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bxCPQmOREfGaD418Sxm7uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sAv_IGOREfGaD418Sxm7uA" name="não" target="_sAeSUGOREfGaD418Sxm7uA" source="_ofCy8GOREfGaD418Sxm7uA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sAv_IWOREfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_sAv_ImOREfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BcUI0GOSEfGaD418Sxm7uA" name="sim" target="_B47zYGOSEfGaD418Sxm7uA" source="_ofCy8GOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BcUI0WOSEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BcUI0mOSEfGaD418Sxm7uA" name="precisaOutroSim" content="return Boolean.TRUE.equals(atendimento.precisaOutroServico)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_E3L18HJ0EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HBoLgGOSEfGaD418Sxm7uA" name="sim" target="_QG7OcHG8EfGBPZMgfyOTVw" source="_B47zYGOSEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HBr14GOSEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_HBr14WOSEfGaD418Sxm7uA" name="lenteContatoSim" content="return Boolean.TRUE.equals(atendimento.lenteContato)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QsnL0HJ0EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aLIzAGOSEfGaD418Sxm7uA" target="_gqhGsGOREfGaD418Sxm7uA" source="_KOY34GOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aLKBIGOSEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_aLKBIWOSEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_by5bAGOSEfGaD418Sxm7uA" target="_gqhGsGOREfGaD418Sxm7uA" source="_Jwk6gGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_by6CEGOSEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_by6CEWOSEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8dN1QG6MEfGFG66_bEuG_g" target="_9DP6gG6MEfGFG66_bEuG_g" source="_pVEEgGquEfGJ4sykcPaQUw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8dN1QW6MEfGFG66_bEuG_g"/>
        <condition xmi:type="expression:Expression" xmi:id="_8dN1Qm6MEfGFG66_bEuG_g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Gj-p4G6NEfGFG66_bEuG_g" name="não" target="_X5NSIF-sEfGJm-VfRlIdsQ" source="_9DP6gG6MEfGFG66_bEuG_g" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GkDiYG6NEfGFG66_bEuG_g"/>
        <condition xmi:type="expression:Expression" xmi:id="_GkEJcG6NEfGFG66_bEuG_g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KYOXkG6NEfGFG66_bEuG_g" name="sim" target="_zt3xoFPUEfG9dLD7G3QBDg" source="_9DP6gG6MEfGFG66_bEuG_g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KYPlsG6NEfGFG66_bEuG_g"/>
        <condition xmi:type="expression:Expression" xmi:id="_KYPlsW6NEfGFG66_bEuG_g" name="servicoAutorizadoSim" content="return Boolean.TRUE.equals(atendimento.servicoAutorizadoPlano)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tEAvQG6PEfGFG66_bEuG_g" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WcnlMHG8EfGBPZMgfyOTVw" target="_eZxokGOQEfGaD418Sxm7uA" source="_QG7OcHG8EfGBPZMgfyOTVw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WcoMQHG8EfGBPZMgfyOTVw"/>
        <condition xmi:type="expression:Expression" xmi:id="_WcoMQXG8EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_i0choHJ5EfGBPZMgfyOTVw" name="não" target="_topqYGnOEfGG3LJZ6zip9w" source="_B47zYGOSEfGaD418Sxm7uA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_i0zG8HJ5EfGBPZMgfyOTVw"/>
        <condition xmi:type="expression:Expression" xmi:id="_i0zG8XJ5EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_QyYG0FPOEfG9dLD7G3QBDg" documentation="Funcionário(a) que trabalha na recepção, responsável pelo atendimento e agendamento" name="Recepcionista" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_xFzCwGRUEfG-37a2zyZkMg" documentation="Funcionário(a) que trabalha no corpo clínico, responsável pela" name="Médico"/>
      <actors xmi:type="process:Actor" xmi:id="_5TtksGUrEfGEXrYvpS-i_A" name="Atendente de pré-consulta"/>
      <actors xmi:type="process:Actor" xmi:id="_819jcGUrEfGEXrYvpS-i_A" name="Técnico de saúde"/>
      <actors xmi:type="process:Actor" xmi:id="_JTFLcGUsEfGEXrYvpS-i_A" name="Recepcionista (venda de lentes)"/>
      <contract xmi:type="process:Contract" xmi:id="_f4iqOx4XEfG_jsm1Ob_k5A">
        <inputs xmi:type="process:ContractInput" xmi:id="_uNq8cG6DEfGFG66_bEuG_g" name="atendimentoInput" type="COMPLEX" dataReference="atendimento">
          <inputs xmi:type="process:ContractInput" xmi:id="_uNrjgG6DEfGFG66_bEuG_g" name="possuiCadastro" type="BOOLEAN"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_KvtQwG8MEfGgR7pClmI30g" name="motivo">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_Kvt30G8MEfGgR7pClmI30g"/>
          </inputs>
          <inputs xmi:type="process:ContractInput" xmi:id="_LfhkIG8MEfGgR7pClmI30g" name="queixa_principal">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_LfhkIW8MEfGgR7pClmI30g"/>
          </inputs>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f4jRMB4XEfG_jsm1Ob_k5A">
        <name xmi:type="expression:Expression" xmi:id="_f4jRMR4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f4jRMh4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f4jRMx4XEfG_jsm1Ob_k5A">
        <name xmi:type="expression:Expression" xmi:id="_f4jRNB4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f4jRNR4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f4jRNh4XEfG_jsm1Ob_k5A">
        <name xmi:type="expression:Expression" xmi:id="_f4jRNx4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f4jROB4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f4jROR4XEfG_jsm1Ob_k5A">
        <name xmi:type="expression:Expression" xmi:id="_f4jROh4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f4jROx4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f4jRPB4XEfG_jsm1Ob_k5A">
        <name xmi:type="expression:Expression" xmi:id="_f4jRPR4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f4jRPh4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_tmfuQGnOEfGG3LJZ6zip9w" name="Agendar serviço">
      <elements xmi:type="process:StartEvent" xmi:id="_0_36IGnPEfGG3LJZ6zip9w" name="Start1" outgoing="_ce9J0HG2EfGBPZMgfyOTVw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_1ADgUGnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_1AC5QGnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_1ADgUWnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_6EMIkGnPEfGG3LJZ6zip9w" name="profissional específico?" outgoing="_RnKlcGqmEfGJ4sykcPaQUw _VVYjoGqmEfGJ4sykcPaQUw" incoming="_qL4M0HG2EfGBPZMgfyOTVw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_40lh4WnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_40lh4GnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_40mI8GnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_uJIxIGqmEfGJ4sykcPaQUw" name="gateway padrão" outgoing="_WNuU8HG5EfGBPZMgfyOTVw" incoming="_okEmEGqmEfGJ4sykcPaQUw _r5rP8GqmEfGJ4sykcPaQUw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ojn6IGqmEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ojnTEGqmEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ojn6IWqmEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_NqISsGqnEfGJ4sykcPaQUw" name="End4" incoming="_WNuU8HG5EfGBPZMgfyOTVw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_NqPncWqnEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_NqPncGqnEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_NqPncmqnEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_nyQN8GquEfGJ4sykcPaQUw" name="T320 - Agendar serviço com profissional escolhido" outgoing="_r5rP8GqmEfGJ4sykcPaQUw" incoming="_RnKlcGqmEfGJ4sykcPaQUw" actor="_tpwdoGnOEfGG3LJZ6zip9w">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RmkvkGqmEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RmjhcGqmEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RmkvkWqmEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_RqCQwHNNEfGeM5ggmLUPBQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_RqCQwXNNEfGeM5ggmLUPBQ" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RqCQwnNNEfGeM5ggmLUPBQ" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_RqCQw3NNEfGeM5ggmLUPBQ" name="atendimentoInput.horarioEscolhido" content="atendimentoInput?.horarioEscolhido" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDateTime">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_RqCQxHNNEfGeM5ggmLUPBQ" name="atendimentoInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_RqCQxXNNEfGeM5ggmLUPBQ" type="JAVA_METHOD" expression="setHorarioEscolhido">
            <inputTypes>java.time.LocalDateTime</inputTypes>
          </operator>
        </operations>
        <operations xmi:type="expression:Operation" xmi:id="_RqCQxnNNEfGeM5ggmLUPBQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_RqCQx3NNEfGeM5ggmLUPBQ" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RqCQyHNNEfGeM5ggmLUPBQ" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_RqCQyXNNEfGeM5ggmLUPBQ" name="atendimentoInput.profissionalAgendado" content="atendimentoInput?.profissionalAgendado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_RqCQynNNEfGeM5ggmLUPBQ" name="atendimentoInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_RqCQy3NNEfGeM5ggmLUPBQ" type="JAVA_METHOD" expression="setProfissionalAgendado">
            <inputTypes>java.lang.String</inputTypes>
          </operator>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RmkvkmqmEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_Rmkvk2qmEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RmkvlGqmEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RmlWoGqmEfGJ4sykcPaQUw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RmkvlWqmEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_nye3d2quEfGJ4sykcPaQUw">
          <targetForm xmi:type="expression:Expression" xmi:id="_w7AT8HM6EfGeM5ggmLUPBQ" name="formAgendarComProfissionalEspecifico" content="f4121f7d-816b-4c78-b6d1-7634dd5ba8f2" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_nye3dmquEfGJ4sykcPaQUw">
          <inputs xmi:type="process:ContractInput" xmi:id="_RqBCoHNNEfGeM5ggmLUPBQ" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_RqBCoXNNEfGeM5ggmLUPBQ" name="horarioEscolhido" type="LOCALDATETIME" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_RqBConNNEfGeM5ggmLUPBQ" name="profissionalAgendado" createMode="false"/>
          </inputs>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_nyfegGquEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_oFWJEGquEfGJ4sykcPaQUw" name="T330 - Agendar serviço com profissional disponível" outgoing="_okEmEGqmEfGJ4sykcPaQUw" incoming="_VVYjoGqmEfGJ4sykcPaQUw" actor="_tpwdoGnOEfGG3LJZ6zip9w">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_VU40YWqmEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_VU40YGqmEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_VU40YmqmEfGJ4sykcPaQUw" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_coAvUnNPEfGeM5ggmLUPBQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_coAvU3NPEfGeM5ggmLUPBQ" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_coAvVHNPEfGeM5ggmLUPBQ" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_coAvVXNPEfGeM5ggmLUPBQ" name="atendimentoInput.horarioEscolhido" content="atendimentoInput?.horarioEscolhido" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDateTime">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_coAvVnNPEfGeM5ggmLUPBQ" name="atendimentoInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_coAvV3NPEfGeM5ggmLUPBQ" type="JAVA_METHOD" expression="setHorarioEscolhido">
            <inputTypes>java.time.LocalDateTime</inputTypes>
          </operator>
        </operations>
        <operations xmi:type="expression:Operation" xmi:id="_coAvWHNPEfGeM5ggmLUPBQ">
          <leftOperand xmi:type="expression:Expression" xmi:id="_coAvWXNPEfGeM5ggmLUPBQ" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_coAvWnNPEfGeM5ggmLUPBQ" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_coAvW3NPEfGeM5ggmLUPBQ" name="atendimentoInput.profissionalAgendado" content="atendimentoInput?.profissionalAgendado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_coAvXHNPEfGeM5ggmLUPBQ" name="atendimentoInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_coAvXXNPEfGeM5ggmLUPBQ" type="JAVA_METHOD" expression="setProfissionalAgendado">
            <inputTypes>java.lang.String</inputTypes>
          </operator>
        </operations>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_VU40ZGqmEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VU40ZWqmEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_VU40Z2qmEfGJ4sykcPaQUw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_VU40ZmqmEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_oFZzeWquEfGJ4sykcPaQUw">
          <targetForm xmi:type="expression:Expression" xmi:id="_5qd-cHM6EfGeM5ggmLUPBQ" name="formAgendarComProfissionalDisponivel" content="b0ccc1ad-bf13-4e31-8802-1b5bf8f92503" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_oFZzeGquEfGJ4sykcPaQUw">
          <inputs xmi:type="process:ContractInput" xmi:id="_coAIQHNPEfGeM5ggmLUPBQ" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_coAvUHNPEfGeM5ggmLUPBQ" name="horarioEscolhido" type="LOCALDATETIME" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_coAvUXNPEfGeM5ggmLUPBQ" name="profissionalAgendado" createMode="false"/>
          </inputs>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_oFaagWquEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_iFpFgHG2EfGBPZMgfyOTVw" name="T310 - Informar preferência de agendamento" outgoing="_qL4M0HG2EfGBPZMgfyOTVw" incoming="_ce9J0HG2EfGBPZMgfyOTVw" actor="_tpwdoGnOEfGG3LJZ6zip9w">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ceAHkHG2EfGBPZMgfyOTVw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_cd_ggHG2EfGBPZMgfyOTVw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ceAuoHG2EfGBPZMgfyOTVw" name="" content="" returnTypeFixed="true"/>
        <operations xmi:type="expression:Operation" xmi:id="_1BfEcHG2EfGBPZMgfyOTVw">
          <leftOperand xmi:type="expression:Expression" xmi:id="_1BfEcXG2EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1BfEcnG2EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_1BfEc3G2EfGBPZMgfyOTVw" name="atendimentoInput.profissionalEspecifico" content="atendimentoInput?.profissionalEspecifico" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_1BfEdHG2EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_1BfEdXG2EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setProfissionalEspecifico">
            <inputTypes>java.lang.Boolean</inputTypes>
          </operator>
        </operations>
        <operations xmi:type="expression:Operation" xmi:id="_1BfEdnG2EfGBPZMgfyOTVw">
          <leftOperand xmi:type="expression:Expression" xmi:id="_1BfEd3G2EfGBPZMgfyOTVw" name="atendimento" content="atendimento" type="TYPE_VARIABLE" returnType="clinicaOlho.model.AtendimentoOftalmologico">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1BfEeHG2EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_1BfEeXG2EfGBPZMgfyOTVw" name="atendimentoInput.profissionalSolicitado" content="atendimentoInput?.profissionalSolicitado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
            <referencedElements xmi:type="process:ContractInput" xmi:id="_1BfEenG2EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" createMode="false"/>
          </rightOperand>
          <operator xmi:type="expression:Operator" xmi:id="_1BfEe3G2EfGBPZMgfyOTVw" type="JAVA_METHOD" expression="setProfissionalSolicitado">
            <inputTypes>java.lang.String</inputTypes>
          </operator>
        </operations>
        <loopCondition xmi:type="expression:Expression" xmi:id="_ceAuoXG2EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_ceAuonG2EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ceAuo3G2EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_ceAupXG2EfGBPZMgfyOTVw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_ceAupHG2EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_iFq6sHG2EfGBPZMgfyOTVw">
          <targetForm xmi:type="expression:Expression" xmi:id="_BUlxgHM7EfGeM5ggmLUPBQ" name="formPreferenciaDeAgendamento" content="804d4f24-0e1b-40b1-af6c-de5c9fc210c0" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_iFqTqHG2EfGBPZMgfyOTVw">
          <inputs xmi:type="process:ContractInput" xmi:id="_1BedYHG2EfGBPZMgfyOTVw" name="atendimentoInput" type="COMPLEX" dataReference="atendimento" createMode="false">
            <inputs xmi:type="process:ContractInput" xmi:id="_1BedYXG2EfGBPZMgfyOTVw" name="profissionalEspecifico" type="BOOLEAN" createMode="false"/>
            <inputs xmi:type="process:ContractInput" xmi:id="_1BedYnG2EfGBPZMgfyOTVw" name="profissionalSolicitado" createMode="false"/>
          </inputs>
        </contract>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_iFq6snG2EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_ggFhUG9jEfGtvrE_zk-BVg" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico">
        <defaultValue xmi:type="expression:Expression" xmi:id="_zP7ZsG9lEfGtvrE_zk-BVg" name="initAtendimento()" content="def atendimentoOftalmologicoVar = new clinicaOlho.model.AtendimentoOftalmologico()&#xA;atendimentoOftalmologicoVar.horarioEscolhido = atendimentoInput?.horarioEscolhido&#xA;atendimentoOftalmologicoVar.profissionalEspecifico = atendimentoInput?.profissionalEspecifico&#xA;atendimentoOftalmologicoVar.profissionalSolicitado = atendimentoInput?.profissionalSolicitado&#xA;return atendimentoOftalmologicoVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="clinicaOlho.model.AtendimentoOftalmologico">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_zP7ZsW9lEfGtvrE_zk-BVg" name="atendimentoInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_toggcGnOEfGG3LJZ6zip9w">
        <targetForm xmi:type="expression:Expression" xmi:id="_XnUzwHM7EfGeM5ggmLUPBQ" name="formSubprocessoAgendarServico" content="0dfc505f-b4c7-4bec-b2ee-8069ad9876a5" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_toggcmnOEfGG3LJZ6zip9w">
        <targetForm xmi:type="expression:Expression" xmi:id="_toggc2nOEfGG3LJZ6zip9w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RnKlcGqmEfGJ4sykcPaQUw" name="sim" target="_nyQN8GquEfGJ4sykcPaQUw" source="_6EMIkGnPEfGG3LJZ6zip9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RnLMgGqmEfGJ4sykcPaQUw"/>
        <condition xmi:type="expression:Expression" xmi:id="_RnLMgWqmEfGJ4sykcPaQUw" name="profissionalEspecifico" content="return Boolean.TRUE.equals(atendimento.profissionalEspecifico)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FmmckHG3EfGBPZMgfyOTVw" name="atendimento" dataType="_f4jRRx4XEfG_jsm1Ob_k5A" className="clinicaOlho.model.AtendimentoOftalmologico"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VVYjoGqmEfGJ4sykcPaQUw" name="não" target="_oFWJEGquEfGJ4sykcPaQUw" source="_6EMIkGnPEfGG3LJZ6zip9w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VVZKsGqmEfGJ4sykcPaQUw"/>
        <condition xmi:type="expression:Expression" xmi:id="_VVZKsWqmEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_okEmEGqmEfGJ4sykcPaQUw" target="_uJIxIGqmEfGJ4sykcPaQUw" source="_oFWJEGquEfGJ4sykcPaQUw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_okHpYGqmEfGJ4sykcPaQUw"/>
        <condition xmi:type="expression:Expression" xmi:id="_okHpYWqmEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_r5rP8GqmEfGJ4sykcPaQUw" target="_uJIxIGqmEfGJ4sykcPaQUw" source="_nyQN8GquEfGJ4sykcPaQUw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_r5wIcGqmEfGJ4sykcPaQUw"/>
        <condition xmi:type="expression:Expression" xmi:id="_r5wvgGqmEfGJ4sykcPaQUw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ce9J0HG2EfGBPZMgfyOTVw" target="_iFpFgHG2EfGBPZMgfyOTVw" source="_0_36IGnPEfGG3LJZ6zip9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ce-X8HG2EfGBPZMgfyOTVw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ce-X8XG2EfGBPZMgfyOTVw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qL4M0HG2EfGBPZMgfyOTVw" target="_6EMIkGnPEfGG3LJZ6zip9w" source="_iFpFgHG2EfGBPZMgfyOTVw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qL5a8HG2EfGBPZMgfyOTVw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qL5a8XG2EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WNuU8HG5EfGBPZMgfyOTVw" target="_NqISsGqnEfGJ4sykcPaQUw" source="_uJIxIGqmEfGJ4sykcPaQUw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WNwKIHG5EfGBPZMgfyOTVw"/>
        <condition xmi:type="expression:Expression" xmi:id="_WNwxMHG5EfGBPZMgfyOTVw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_tpwdoGnOEfGG3LJZ6zip9w" documentation="Funcionário(a) que trabalha na recepção, responsável pelo atendimento e agendamento" name="Recepcionista" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_tohukGnOEfGG3LJZ6zip9w">
        <inputs xmi:type="process:ContractInput" xmi:id="_zP6LkG9lEfGtvrE_zk-BVg" name="atendimentoInput" type="COMPLEX" dataReference="atendimento">
          <inputs xmi:type="process:ContractInput" xmi:id="_zP6LkW9lEfGtvrE_zk-BVg" name="horarioEscolhido"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_zP6Lkm9lEfGtvrE_zk-BVg" name="profissionalEspecifico" type="BOOLEAN"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_zP6Lk29lEfGtvrE_zk-BVg" name="profissionalSolicitado"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_toerQGnOEfGG3LJZ6zip9w">
        <name xmi:type="expression:Expression" xmi:id="_tofSUGnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tof5YGnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tof5YWnOEfGG3LJZ6zip9w">
        <name xmi:type="expression:Expression" xmi:id="_tof5YmnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tof5Y2nOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tof5ZGnOEfGG3LJZ6zip9w">
        <name xmi:type="expression:Expression" xmi:id="_tof5ZWnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tof5ZmnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tof5Z2nOEfGG3LJZ6zip9w">
        <name xmi:type="expression:Expression" xmi:id="_tof5aGnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tof5aWnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tof5amnOEfGG3LJZ6zip9w">
        <name xmi:type="expression:Expression" xmi:id="_tof5a2nOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tof5bGnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_f4jRPx4XEfG_jsm1Ob_k5A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_f4jRQB4XEfG_jsm1Ob_k5A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_f4jRQR4XEfG_jsm1Ob_k5A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_f4jRQh4XEfG_jsm1Ob_k5A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_f4jRQx4XEfG_jsm1Ob_k5A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_f4jRRB4XEfG_jsm1Ob_k5A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_f4jRRR4XEfG_jsm1Ob_k5A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_f4jRRh4XEfG_jsm1Ob_k5A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_f4jRRx4XEfG_jsm1Ob_k5A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_f4j4QB4XEfG_jsm1Ob_k5A" type="Process" element="_f4iDEB4XEfG_jsm1Ob_k5A" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_f4kfUB4XEfG_jsm1Ob_k5A" type="2007" element="_f4iqIB4XEfG_jsm1Ob_k5A">
      <children xmi:type="notation:DecorationNode" xmi:id="_f4kfUR4XEfG_jsm1Ob_k5A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_f4kfUh4XEfG_jsm1Ob_k5A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_f4kfUx4XEfG_jsm1Ob_k5A" type="3007" element="_f4iqIR4XEfG_jsm1Ob_k5A">
          <children xmi:type="notation:DecorationNode" xmi:id="_f4kfVB4XEfG_jsm1Ob_k5A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_f4kfVR4XEfG_jsm1Ob_k5A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_f4kfWR4XEfG_jsm1Ob_k5A" type="3002" element="_f4iqIh4XEfG_jsm1Ob_k5A" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_f4kfWh4XEfG_jsm1Ob_k5A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_f4kfWx4XEfG_jsm1Ob_k5A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f4kfXB4XEfG_jsm1Ob_k5A" x="44" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_M-xVgFPSEfG9dLD7G3QBDg" type="3008" element="_M-r18FPSEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_M-xVglPSEfG9dLD7G3QBDg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_M-x8kFPSEfG9dLD7G3QBDg" x="11" y="-57"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_M-xVgVPSEfG9dLD7G3QBDg" x="413" y="104" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gAOiUFPUEfG9dLD7G3QBDg" type="3008" element="_gAK38FPUEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_gAPwcFPUEfG9dLD7G3QBDg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gAPwcVPUEfG9dLD7G3QBDg" y="-63"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gAOiUVPUEfG9dLD7G3QBDg" x="122" y="60" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xvv4EFPUEfG9dLD7G3QBDg" type="3008" element="_xvtb0FPUEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_xvxGMFPUEfG9dLD7G3QBDg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xvxGMVPUEfG9dLD7G3QBDg" x="1" y="-58"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xvv4EVPUEfG9dLD7G3QBDg" x="548" y="104" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zt4_w1PUEfG9dLD7G3QBDg" type="3008" element="_zt3xoFPUEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_zt4_xVPUEfG9dLD7G3QBDg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_zt5m0FPUEfG9dLD7G3QBDg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zt4_xFPUEfG9dLD7G3QBDg" x="721" y="292" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6SSVMFfXEfGaAKjg7KE34A" type="3008" element="_6SE50FfXEfGaAKjg7KE34A" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_6SUxcFfXEfGaAKjg7KE34A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6SUxcVfXEfGaAKjg7KE34A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6SS8QFfXEfGaAKjg7KE34A" x="819" y="292"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_X5atgF-sEfGJm-VfRlIdsQ" type="3003" element="_X5NSIF-sEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_X5b7oF-sEfGJm-VfRlIdsQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_X5dJwF-sEfGJm-VfRlIdsQ" x="34" y="-16"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_X5atgV-sEfGJm-VfRlIdsQ" x="970" y="28"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dCKf8GOREfGaD418Sxm7uA" type="3008" element="_dCIDsGOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_dCKf8mOREfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dCKf82OREfGaD418Sxm7uA" y="-64"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dCKf8WOREfGaD418Sxm7uA" x="945" y="293" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ec7NwGOREfGaD418Sxm7uA" type="3008" element="_ec3jYGOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_ec700GOREfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ec700WOREfGaD418Sxm7uA" y="-55"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ec7NwWOREfGaD418Sxm7uA" x="1121" y="293" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gql_MGOREfGaD418Sxm7uA" type="3008" element="_gqhGsGOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_gqn0YGOREfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gqobcGOREfGaD418Sxm7uA" x="-64" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gql_MWOREfGaD418Sxm7uA" x="1432" y="329" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ofHrcGOREfGaD418Sxm7uA" type="3008" element="_ofCy8GOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_ofISgGOREfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ofI5kGOREfGaD418Sxm7uA" x="-89" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ofHrcWOREfGaD418Sxm7uA" x="1432" y="234" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sAjx4GOREfGaD418Sxm7uA" type="3003" element="_sAeSUGOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_sAlAAGOREfGaD418Sxm7uA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sAlAAWOREfGaD418Sxm7uA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sAjx4WOREfGaD418Sxm7uA" x="1564" y="243"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_B4-2sGOSEfGaD418Sxm7uA" type="3008" element="_B47zYGOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_B5Ar4GOSEfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_B5BS8GOSEfGaD418Sxm7uA" y="-60"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_B4-2sWOSEfGaD418Sxm7uA" x="1431" y="146" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JGGvQGOTEfGaD418Sxm7uA" type="3005" element="_JGETAGOTEfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JGH9YGOTEfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JGGvQWOTEfGaD418Sxm7uA" x="202" y="146" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5MNjoGUtEfGEXrYvpS-i_A" type="3005" element="_5MLHYGUtEfGEXrYvpS-i_A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5MP_4GUtEfGEXrYvpS-i_A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5MNjoWUtEfGEXrYvpS-i_A" x="209" y="53" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tostsGnOEfGG3LJZ6zip9w" type="3063" element="_topqYGnOEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tostsmnOEfGG3LJZ6zip9w" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tostsWnOEfGG3LJZ6zip9w" x="927" y="103" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pVGgwGquEfGJ4sykcPaQUw" type="3005" element="_pVEEgGquEfGJ4sykcPaQUw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pVHH0GquEfGJ4sykcPaQUw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pVGgwWquEfGJ4sykcPaQUw" x="687" y="35" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9DWBIG6MEfGFG66_bEuG_g" type="3008" element="_9DP6gG6MEfGFG66_bEuG_g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_9DXPQG6MEfGFG66_bEuG_g" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_9DXPQW6MEfGFG66_bEuG_g" x="-65" y="-26"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9DWBIW6MEfGFG66_bEuG_g" x="721" y="176" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_f4kfXR4XEfG_jsm1Ob_k5A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_f4kfXh4XEfG_jsm1Ob_k5A" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_f4kfXx4XEfG_jsm1Ob_k5A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_f4kfYB4XEfG_jsm1Ob_k5A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f4kfYR4XEfG_jsm1Ob_k5A" x="19" y="10" width="1697" height="434"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_k29kkB4aEfG2S7DpaDzKGg" type="3007" element="_k2ts8B4aEfG2S7DpaDzKGg">
          <children xmi:type="notation:DecorationNode" xmi:id="_k3BO8B4aEfG2S7DpaDzKGg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_k3BO8R4aEfG2S7DpaDzKGg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_ULxY8GOPEfGaD418Sxm7uA" type="3005" element="_ULXJQGOPEfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ULz1MGOPEfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ULyAAGOPEfGaD418Sxm7uA" x="1211" y="38" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Jwok4GOREfGaD418Sxm7uA" type="3005" element="_Jwk6gGOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JwqaEGOREfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Jwok4WOREfGaD418Sxm7uA" x="666" y="104" width="140" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_k2-LoB4aEfG2S7DpaDzKGg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_k2-LoR4aEfG2S7DpaDzKGg" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_k2-Loh4aEfG2S7DpaDzKGg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_k3BO8h4aEfG2S7DpaDzKGg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_k2-Lox4aEfG2S7DpaDzKGg" x="44" y="434" width="1807" height="224"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_lLUD8B4aEfG2S7DpaDzKGg" type="3007" element="_lLRnsB4aEfG2S7DpaDzKGg">
          <children xmi:type="notation:DecorationNode" xmi:id="_lLV5IB4aEfG2S7DpaDzKGg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_lLV5IR4aEfG2S7DpaDzKGg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_3IMdsF-sEfGJm-VfRlIdsQ" type="3005" element="_3IDTwF-sEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3IQIEF-sEfGJm-VfRlIdsQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3IMdsV-sEfGJm-VfRlIdsQ" x="189" y="58" width="140" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_lLUD8R4aEfG2S7DpaDzKGg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_lLUD8h4aEfG2S7DpaDzKGg" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_lLUD8x4aEfG2S7DpaDzKGg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_lLV5Ih4aEfG2S7DpaDzKGg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lLUD9B4aEfG2S7DpaDzKGg" x="19" y="629" width="1697" height="175"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_KkbpYF-sEfGJm-VfRlIdsQ" type="3007" element="_KkU7sF-sEfGJm-VfRlIdsQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_KkcQcF-sEfGJm-VfRlIdsQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_KkcQcV-sEfGJm-VfRlIdsQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_KOgMoGOREfGaD418Sxm7uA" type="3005" element="_KOY34GOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KOgzsGOREfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KOgMoWOREfGaD418Sxm7uA" x="805" y="63" width="140" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_KkbpYV-sEfGJm-VfRlIdsQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_KkbpYl-sEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_KkbpY1-sEfGJm-VfRlIdsQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_KkcQcl-sEfGJm-VfRlIdsQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KkbpZF-sEfGJm-VfRlIdsQ" x="19" y="776" width="1697" height="175"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_kFj6QF-sEfGJm-VfRlIdsQ" type="3007" element="_kFheAF-sEfGJm-VfRlIdsQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_kFkhUF-sEfGJm-VfRlIdsQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_kFlIYF-sEfGJm-VfRlIdsQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Ykmk8GOQEfGaD418Sxm7uA" type="3003" element="_YkOxgGOQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_YknzEGOQEfGaD418Sxm7uA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_YknzEWOQEfGaD418Sxm7uA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ykmk8WOQEfGaD418Sxm7uA" x="319" y="158"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eZ0r4GOQEfGaD418Sxm7uA" type="3008" element="_eZxokGOQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_eZ1S8GOQEfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_eZ1S8WOQEfGaD418Sxm7uA" y="-60"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eZ0r4WOQEfGaD418Sxm7uA" x="240" y="62" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NLTDAGOTEfGaD418Sxm7uA" type="3005" element="_NLOxkGOTEfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NLTDAmOTEfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NLTDAWOTEfGaD418Sxm7uA" x="358" y="59" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QHE_cHG8EfGBPZMgfyOTVw" type="3005" element="_QG7OcHG8EfGBPZMgfyOTVw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QHHbsHG8EfGBPZMgfyOTVw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QHE_cXG8EfGBPZMgfyOTVw" x="77" y="59" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_kFj6QV-sEfGJm-VfRlIdsQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_kFj6Ql-sEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_kFj6Q1-sEfGJm-VfRlIdsQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_kFlvcF-sEfGJm-VfRlIdsQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kFj6RF-sEfGJm-VfRlIdsQ" x="44" y="987" width="1807" height="230"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_f4kfYh4XEfG_jsm1Ob_k5A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_f4kfYx4XEfG_jsm1Ob_k5A" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_f4kfZB4XEfG_jsm1Ob_k5A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_f4kfZR4XEfG_jsm1Ob_k5A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f4kfZh4XEfG_jsm1Ob_k5A" width="1826" height="278"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_tokx4GnOEfGG3LJZ6zip9w" type="2007" element="_tmfuQGnOEfGG3LJZ6zip9w">
      <children xmi:type="notation:DecorationNode" xmi:id="_ton1MGnOEfGG3LJZ6zip9w" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_ton1MWnOEfGG3LJZ6zip9w" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_1ANRUGnPEfGG3LJZ6zip9w" type="3002" element="_0_36IGnPEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_1AQUoGnPEfGG3LJZ6zip9w" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_1AQ7sGnPEfGG3LJZ6zip9w" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1AN4YGnPEfGG3LJZ6zip9w" x="79" y="92"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_6EQaAGnPEfGG3LJZ6zip9w" type="3008" element="_6EMIkGnPEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_6ERBEGnPEfGG3LJZ6zip9w" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_6ERBEWnPEfGG3LJZ6zip9w" y="-63"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6EQaAWnPEfGG3LJZ6zip9w" x="405" y="85" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_uJQs8GqmEfGJ4sykcPaQUw" type="3008" element="_uJIxIGqmEfGJ4sykcPaQUw" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_uJU-YGqmEfGJ4sykcPaQUw" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_uJWMgGqmEfGJ4sykcPaQUw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uJR7EGqmEfGJ4sykcPaQUw" x="816" y="85" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_NqgtMGqnEfGJ4sykcPaQUw" type="3003" element="_NqISsGqnEfGJ4sykcPaQUw" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_NqiiYGqnEfGJ4sykcPaQUw" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_NqiiYWqnEfGJ4sykcPaQUw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NqgtMWqnEfGJ4sykcPaQUw" x="946" y="91"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_nyk-EGquEfGJ4sykcPaQUw" type="3005" element="_nyQN8GquEfGJ4sykcPaQUw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_nyoocGquEfGJ4sykcPaQUw" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nyk-EWquEfGJ4sykcPaQUw" x="568" y="32" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_oFbBkGquEfGJ4sykcPaQUw" type="3005" element="_oFWJEGquEfGJ4sykcPaQUw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_oFcPsGquEfGJ4sykcPaQUw" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oFbBkWquEfGJ4sykcPaQUw" x="567" y="125" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_iFsv4HG2EfGBPZMgfyOTVw" type="3005" element="_iFpFgHG2EfGBPZMgfyOTVw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_iFt-AHG2EfGBPZMgfyOTVw" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iFsv4XG2EfGBPZMgfyOTVw" x="180" y="70" width="140" height="70"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_tolY8GnOEfGG3LJZ6zip9w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_tomAAGnOEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_tomAAWnOEfGG3LJZ6zip9w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_ton1MmnOEfGG3LJZ6zip9w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tomAAmnOEfGG3LJZ6zip9w" width="1886" height="316"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_f4kfZx4XEfG_jsm1Ob_k5A"/>
    <edges xmi:type="notation:Connector" xmi:id="_bh_j0FPREfG9dLD7G3QBDg" type="4001" element="_bh6rUFPREfG9dLD7G3QBDg" source="_f4kfWR4XEfG_jsm1Ob_k5A" target="_gAOiUFPUEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_biAK4FPREfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_biAK4VPREfG9dLD7G3QBDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bh_j0VPREfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bh_j0lPREfG9dLD7G3QBDg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rjqQoFPREfG9dLD7G3QBDg" type="4001" element="_rjkxEFPREfG9dLD7G3QBDg" source="_gAOiUFPUEfG9dLD7G3QBDg" target="_5MNjoGUtEfGEXrYvpS-i_A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rjq3sFPREfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rjq3sVPREfG9dLD7G3QBDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rjqQoVPREfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rjqQolPREfG9dLD7G3QBDg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9B8FYFPREfG9dLD7G3QBDg" type="4001" element="_9BqYkFPREfG9dLD7G3QBDg" source="_gAOiUFPUEfG9dLD7G3QBDg" target="_JGGvQGOTEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9B8scFPREfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9B8scVPREfG9dLD7G3QBDg" x="-2" y="-16"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9B8FYVPREfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9B8FYlPREfG9dLD7G3QBDg" points="[6, 6, -68, -89]$[6, 83, -68, -12]$[65, 83, -9, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BrMIcFPSEfG9dLD7G3QBDg" id="(0.3488372093023256,0.8604651162790697)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ac8zsFPSEfG9dLD7G3QBDg" id="(0.08,0.78)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Gh6m0FPSEfG9dLD7G3QBDg" type="4001" element="_Gh28cFPSEfG9dLD7G3QBDg" source="_JGGvQGOTEfGaD418Sxm7uA" target="_M-xVgFPSEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Gh7N4FPSEfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Gh7N4VPSEfG9dLD7G3QBDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Gh6m0VPSEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Gh6m0lPSEfG9dLD7G3QBDg" points="[3, 0, -84, 49]$[38, 0, -49, 49]$[38, -49, -49, 0]$[66, -49, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HOziAFPSEfG9dLD7G3QBDg" id="(0.98,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IfZAIFPSEfG9dLD7G3QBDg" type="4001" element="_IfUHoFPSEfG9dLD7G3QBDg" source="_5MNjoGUtEfGEXrYvpS-i_A" target="_M-xVgFPSEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IfZnMFPSEfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IfaOQFPSEfG9dLD7G3QBDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IfZAIVPSEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IfZAIlPSEfG9dLD7G3QBDg" points="[0, 2, -77, -44]$[28, 2, -49, -44]$[28, 46, -49, 0]$[56, 46, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IfgU4FPSEfG9dLD7G3QBDg" id="(1.0,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_R1U0wFPSEfG9dLD7G3QBDg" type="4001" element="_R1S_kFPSEfG9dLD7G3QBDg" source="_M-xVgFPSEfG9dLD7G3QBDg" target="_xvv4EFPUEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_R1WC4FPSEfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_R1WC4VPSEfG9dLD7G3QBDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_R1U0wVPSEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_R1U0wlPSEfG9dLD7G3QBDg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZoWsMFPSEfG9dLD7G3QBDg" type="4001" element="_ZoTo4FPSEfG9dLD7G3QBDg" source="_xvv4EFPUEfG9dLD7G3QBDg" target="_pVGgwGquEfGJ4sykcPaQUw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZoXTQFPSEfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZoXTQVPSEfG9dLD7G3QBDg" x="7" y="-32"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZoWsMVPSEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZoWsMlPSEfG9dLD7G3QBDg" points="[22, 0, -154, 58]$[90, 0, -86, 58]$[90, -63, -86, -5]$[106, -63, -70, -5]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tDJmEFPUEfG9dLD7G3QBDg" type="4001" element="_tDF7sFPUEfG9dLD7G3QBDg" source="_xvv4EFPUEfG9dLD7G3QBDg" target="_zt4_w1PUEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tDMCUFPUEfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tDMCUVPUEfG9dLD7G3QBDg" x="-36" y="28"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tDJmEVPUEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tDJmElPUEfG9dLD7G3QBDg" points="[11, 16, -173, -166]$[11, 182, -173, 0]$[163, 182, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tDSwAFPUEfG9dLD7G3QBDg" id="(0.23255813953488372,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EAamYFfjEfGaAKjg7KE34A" type="4001" element="_EAUfwFfjEfGaAKjg7KE34A" source="_zt4_w1PUEfG9dLD7G3QBDg" target="_6SSVMFfXEfGaAKjg7KE34A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EAcbkFfjEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EAdCoFfjEfGaAKjg7KE34A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EAamYVfjEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EAamYlfjEfGaAKjg7KE34A" points="[-6, 0, -82, 6]$[75, 14, -1, 20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EAjJQFfjEfGaAKjg7KE34A" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_K0AaEFfjEfGaAKjg7KE34A" type="4001" element="_Kz_L8FfjEfGaAKjg7KE34A" source="_6SSVMFfXEfGaAKjg7KE34A" target="_dCKf8GOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_K0C2UFfjEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_K0DdYFfjEfGaAKjg7KE34A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_K0AaEVfjEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_K0AaElfjEfGaAKjg7KE34A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Ox7oMFfjEfGaAKjg7KE34A" type="4001" element="_Oxlp8FfjEfGaAKjg7KE34A" source="_6SSVMFfXEfGaAKjg7KE34A" target="_tostsGnOEfGG3LJZ6zip9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ox8PQFfjEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ox8PQVfjEfGaAKjg7KE34A" x="10" y="7"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ox7oMVfjEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ox7oMlfjEfGaAKjg7KE34A" points="[-22, -30, -137, 164]$[-22, -114, -137, 80]$[114, -114, -1, 80]$[114, -169, -1, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OyAgsFfjEfGaAKjg7KE34A" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lmwD01fjEfGaAKjg7KE34A" type="4001" element="_lmwD0FfjEfGaAKjg7KE34A" source="_dCKf8GOREfGaD418Sxm7uA" target="_3IMdsF-sEfGJm-VfRlIdsQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lmwq4FfjEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lmwq4VfjEfGaAKjg7KE34A" x="184" y="-5"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lmwD1FfjEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lmwD1VfjEfGaAKjg7KE34A" points="[0, 22, 707, -415]$[0, 160, 707, -277]$[-718, 160, -11, -277]$[-718, 402, -11, -35]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0w-yUFfjEfGaAKjg7KE34A" type="4001" element="_0w-LQFfjEfGaAKjg7KE34A" source="_dCKf8GOREfGaD418Sxm7uA" target="_ec7NwGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0w_ZYFfjEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0w_ZYVfjEfGaAKjg7KE34A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0w-yUVfjEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0w-yUlfjEfGaAKjg7KE34A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_A7BGQlfkEfGaAKjg7KE34A" type="4001" element="_A7AfMFfkEfGaAKjg7KE34A" source="_ec7NwGOREfGaD418Sxm7uA" target="_ULxY8GOPEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_A7BGRVfkEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_A7BGRlfkEfGaAKjg7KE34A" x="-16" y="54"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_A7BGQ1fkEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_A7BGRFfkEfGaAKjg7KE34A" points="[20, -1, -109, -189]$[125, -1, -4, -189]$[125, 158, -4, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_X50WIF-sEfGJm-VfRlIdsQ" type="4001" element="_X5yg8F-sEfGJm-VfRlIdsQ" source="_tostsGnOEfGG3LJZ6zip9w" target="_X5atgF-sEfGJm-VfRlIdsQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_X50WI1-sEfGJm-VfRlIdsQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_X50WJF-sEfGJm-VfRlIdsQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_X50WIV-sEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_X50WIl-sEfGJm-VfRlIdsQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lPpJoGOPEfGaD418Sxm7uA" type="4001" element="_lPn7gGOPEfGaD418Sxm7uA" source="_ec7NwGOREfGaD418Sxm7uA" target="_KOgMoGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lPq-0GOPEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lPq-0WOPEfGaD418Sxm7uA" x="-350" y="15"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lPpJoWOPEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lPpJomOPEfGaD418Sxm7uA" points="[-21, 33, 277, -590]$[-21, 507, 277, -116]$[-307, 507, -9, -116]$[-307, 593, -9, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mdcZgGOPEfGaD418Sxm7uA" id="(0.9767441860465116,0.23255813953488372)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5yKLcGOPEfGaD418Sxm7uA" type="4001" element="_5yIWQGOPEfGaD418Sxm7uA" source="_dCKf8GOREfGaD418Sxm7uA" target="_QHE_cHG8EfGBPZMgfyOTVw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5yKygGOPEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5yKygWOPEfGaD418Sxm7uA" x="40" y="9"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5yKLcWOPEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5yKLcmOPEfGaD418Sxm7uA" points="[0, 22, 829, -761]$[0, 104, 829, -679]$[-847, 104, -18, -679]$[-847, 753, -18, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VEyPImOQEfGaD418Sxm7uA" type="4001" element="_VEwZ8GOQEfGaD418Sxm7uA" source="_eZ0r4GOQEfGaD418Sxm7uA" target="_NLTDAGOTEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VEy2MmOQEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VEy2M2OQEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VEy2MGOQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VEy2MWOQEfGaD418Sxm7uA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YlA0oGOQEfGaD418Sxm7uA" type="4001" element="_Yk-_cGOQEfGaD418Sxm7uA" source="_NLTDAGOTEfGaD418Sxm7uA" target="_Ykmk8GOQEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YlA0o2OQEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YlA0pGOQEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YlA0oWOQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YlA0omOQEfGaD418Sxm7uA" points="[-1, 25, 73, -64]$[-1, 88, 73, -1]$[-60, 88, 14, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aMpg0GOQEfGaD418Sxm7uA" type="4001" element="_aMnEkGOQEfGaD418Sxm7uA" source="_eZ0r4GOQEfGaD418Sxm7uA" target="_Ykmk8GOQEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aMqH4GOQEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aMqH4WOQEfGaD418Sxm7uA" x="-31" y="13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aMpg0WOQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aMpg0mOQEfGaD418Sxm7uA" points="[-22, 13, -73, -68]$[-22, 81, -73, 0]$[36, 81, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aMyqwGOQEfGaD418Sxm7uA" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gWRxgmOQEfGaD418Sxm7uA" type="4001" element="_gWRKcGOQEfGaD418Sxm7uA" source="_3IMdsF-sEfGJm-VfRlIdsQ" target="_Jwok4GOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gWSYkGOQEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gWSYkWOQEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gWRxg2OQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gWRxhGOQEfGaD418Sxm7uA" points="[60, -1, -407, 161]$[234, -1, -233, 161]$[234, -159, -233, 3]$[417, -159, -50, 3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PXk_QGOREfGaD418Sxm7uA" type="4001" element="_PXjxIGOREfGaD418Sxm7uA" source="_ULxY8GOPEfGaD418Sxm7uA" target="_gql_MGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PXlmUGOREfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PXlmUWOREfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PXk_QWOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PXk_QmOREfGaD418Sxm7uA" points="[60, -1, -122, 151]$[178, -1, -4, 151]$[178, -135, -4, 17]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bxC2UGOREfGaD418Sxm7uA" type="4001" element="_bxCPQGOREfGaD418Sxm7uA" source="_gql_MGOREfGaD418Sxm7uA" target="_ofHrcGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bxC2U2OREfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bxC2VGOREfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bxC2UWOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bxC2UmOREfGaD418Sxm7uA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sAzCcGOREfGaD418Sxm7uA" type="4001" element="_sAv_IGOREfGaD418Sxm7uA" source="_ofHrcGOREfGaD418Sxm7uA" target="_sAjx4GOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sAzCc2OREfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sAzCdGOREfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sAzCcWOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sAzCcmOREfGaD418Sxm7uA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BciyUGOSEfGaD418Sxm7uA" type="4001" element="_BcUI0GOSEfGaD418Sxm7uA" source="_ofHrcGOREfGaD418Sxm7uA" target="_B4-2sGOSEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BcjZYGOSEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BcjZYWOSEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BciyUWOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BciyUmOSEfGaD418Sxm7uA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HBwHUGOSEfGaD418Sxm7uA" type="4001" element="_HBoLgGOSEfGaD418Sxm7uA" source="_B4-2sGOSEfGaD418Sxm7uA" target="_QHE_cHG8EfGBPZMgfyOTVw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HBx8gGOSEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HBx8gWOSEfGaD418Sxm7uA" x="-110" y="877"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HBwuYGOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HBwuYWOSEfGaD418Sxm7uA" points="[40, -10, 1347, -925]$[281, -10, 1588, -925]$[281, 857, 1588, -58]$[-1287, 857, 20, -58]$[-1287, 890, 20, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HB6fYGOSEfGaD418Sxm7uA" id="(0.06976744186046512,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aLL2UGOSEfGaD418Sxm7uA" type="4001" element="_aLIzAGOSEfGaD418Sxm7uA" source="_KOgMoGOREfGaD418Sxm7uA" target="_gql_MGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aLO5oGOSEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aLO5oWOSEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aLL2UWOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aLL2UmOSEfGaD418Sxm7uA" points="[0, -6, -511, 566]$[504, -6, -7, 566]$[504, -569, -7, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aLTLEGOSEfGaD418Sxm7uA" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xc_5IGqnEfGJ4sykcPaQUw" id="(0.627906976744186,0.8372093023255814)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_by7QMGOSEfGaD418Sxm7uA" type="4001" element="_by5bAGOSEfGaD418Sxm7uA" source="_Jwok4GOREfGaD418Sxm7uA" target="_gql_MGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_by8eUGOSEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_by8eUWOSEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_by7QMWOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_by7QMmOSEfGaD418Sxm7uA" points="[0, -6, -647, 222]$[643, -6, -4, 222]$[643, -211, -4, 17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_by-6kGOSEfGaD418Sxm7uA" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nfegEGqnEfGJ4sykcPaQUw" id="(0.7906976744186046,0.4418604651162791)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RnMaoGqmEfGJ4sykcPaQUw" type="4001" element="_RnKlcGqmEfGJ4sykcPaQUw" source="_6EQaAGnPEfGG3LJZ6zip9w" target="_nyk-EGquEfGJ4sykcPaQUw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RnNBsGqmEfGJ4sykcPaQUw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RnNBsWqmEfGJ4sykcPaQUw" x="23" y="23"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RnMaoWqmEfGJ4sykcPaQUw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RnMaomqmEfGJ4sykcPaQUw" points="[22, 0, -190, 39]$[96, 0, -116, 39]$[96, -37, -116, 2]$[142, -37, -70, 2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VWD5EGqmEfGJ4sykcPaQUw" type="4001" element="_VVYjoGqmEfGJ4sykcPaQUw" source="_6EQaAGnPEfGG3LJZ6zip9w" target="_oFbBkGquEfGJ4sykcPaQUw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VWEgIGqmEfGJ4sykcPaQUw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VWEgIWqmEfGJ4sykcPaQUw" x="33" y="-22"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VWD5EWqmEfGJ4sykcPaQUw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VWD5EmqmEfGJ4sykcPaQUw" points="[22, 0, -189, -54]$[96, 0, -115, -54]$[96, 50, -115, -4]$[141, 50, -70, -4]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_okKssGqmEfGJ4sykcPaQUw" type="4001" element="_okEmEGqmEfGJ4sykcPaQUw" source="_oFbBkGquEfGJ4sykcPaQUw" target="_uJQs8GqmEfGJ4sykcPaQUw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_okL60GqmEfGJ4sykcPaQUw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_okL60WqmEfGJ4sykcPaQUw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_okKssWqmEfGJ4sykcPaQUw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_okKssmqmEfGJ4sykcPaQUw" points="[70, -1, -152, 53]$[109, -1, -113, 53]$[109, -54, -113, 0]$[201, -54, -21, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_r50Z4GqmEfGJ4sykcPaQUw" type="4001" element="_r5rP8GqmEfGJ4sykcPaQUw" source="_nyk-EGquEfGJ4sykcPaQUw" target="_uJQs8GqmEfGJ4sykcPaQUw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_r52PEGqmEfGJ4sykcPaQUw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_r522IGqmEfGJ4sykcPaQUw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_r51A8GqmEfGJ4sykcPaQUw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_r51A8WqmEfGJ4sykcPaQUw" points="[0, 0, -151, -47]$[38, 0, -113, -47]$[38, 47, -113, 0]$[130, 47, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_r6GtwGqmEfGJ4sykcPaQUw" id="(1.0,0.38571428571428573)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8dPqcG6MEfGFG66_bEuG_g" type="4001" element="_8dN1QG6MEfGFG66_bEuG_g" source="_pVGgwGquEfGJ4sykcPaQUw" target="_9DWBIG6MEfGFG66_bEuG_g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8dQ4kG6MEfGFG66_bEuG_g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8dQ4kW6MEfGFG66_bEuG_g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8dPqcW6MEfGFG66_bEuG_g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8dPqcm6MEfGFG66_bEuG_g" points="[-15, 35, 0, -92]$[-15, 106, 0, -21]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GkMFQG6NEfGFG66_bEuG_g" type="4001" element="_Gj-p4G6NEfGFG66_bEuG_g" source="_9DWBIG6MEfGFG66_bEuG_g" target="_X5atgF-sEfGJm-VfRlIdsQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GkPIkG6NEfGFG66_bEuG_g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GkQWsG6NEfGFG66_bEuG_g" x="1" y="13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GkMFQW6NEfGFG66_bEuG_g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GkMFQm6NEfGFG66_bEuG_g" points="[0, -7, -221, 154]$[97, -7, -124, 154]$[97, -162, -124, -1]$[206, -162, -15, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GkY5kG6NEfGFG66_bEuG_g" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KY-lgG6NEfGFG66_bEuG_g" type="4001" element="_KYOXkG6NEfGFG66_bEuG_g" source="_9DWBIG6MEfGFG66_bEuG_g" target="_zt4_w1PUEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KY_zoG6NEfGFG66_bEuG_g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KY_zoW6NEfGFG66_bEuG_g" y="-14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KY-lgW6NEfGFG66_bEuG_g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KY-lgm6NEfGFG66_bEuG_g" points="[-22, 14, 0, -95]$[-21, 130, 1, 21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KZCP4G6NEfGFG66_bEuG_g" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ce_mEHG2EfGBPZMgfyOTVw" type="4001" element="_ce9J0HG2EfGBPZMgfyOTVw" source="_1ANRUGnPEfGG3LJZ6zip9w" target="_iFsv4HG2EfGBPZMgfyOTVw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cfA0MHG2EfGBPZMgfyOTVw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cfA0MXG2EfGBPZMgfyOTVw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ce_mEXG2EfGBPZMgfyOTVw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ce_mEnG2EfGBPZMgfyOTVw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qMBWwHG2EfGBPZMgfyOTVw" type="4001" element="_qL4M0HG2EfGBPZMgfyOTVw" source="_iFsv4HG2EfGBPZMgfyOTVw" target="_6EQaAGnPEfGG3LJZ6zip9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qMB90HG2EfGBPZMgfyOTVw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qMB90XG2EfGBPZMgfyOTVw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qMBWwXG2EfGBPZMgfyOTVw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qMBWwnG2EfGBPZMgfyOTVw" points="[0, 8, -108, -1]$[104, -8, -4, -17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qMKgsHG2EfGBPZMgfyOTVw" id="(1.0,0.391304347826087)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WNymYHG5EfGBPZMgfyOTVw" type="4001" element="_WNuU8HG5EfGBPZMgfyOTVw" source="_uJQs8GqmEfGJ4sykcPaQUw" target="_NqgtMGqnEfGJ4sykcPaQUw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WN1psHG5EfGBPZMgfyOTVw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WN2QwHG5EfGBPZMgfyOTVw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WNzNcHG5EfGBPZMgfyOTVw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WNzNcXG5EfGBPZMgfyOTVw" points="[-2, -5, -104, 2]$[97, 7, -5, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WN-MkHG5EfGBPZMgfyOTVw" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WcrPkHG8EfGBPZMgfyOTVw" type="4001" element="_WcnlMHG8EfGBPZMgfyOTVw" source="_QHE_cHG8EfGBPZMgfyOTVw" target="_eZ0r4GOQEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Wctr0HG8EfGBPZMgfyOTVw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Wctr0XG8EfGBPZMgfyOTVw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WcrPkXG8EfGBPZMgfyOTVw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WcrPknG8EfGBPZMgfyOTVw" points="[0, -3, -112, 0]$[91, -3, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Wc3c0HG8EfGBPZMgfyOTVw" id="(1.0,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_i1SPIHJ5EfGBPZMgfyOTVw" type="4001" element="_i0choHJ5EfGBPZMgfyOTVw" source="_B4-2sGOSEfGaD418Sxm7uA" target="_tostsGnOEfGG3LJZ6zip9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_i1VScHJ5EfGBPZMgfyOTVw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_i1V5gHJ5EfGBPZMgfyOTVw" x="-4" y="78"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_i1S2MHJ5EfGBPZMgfyOTVw" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_i1S2MXJ5EfGBPZMgfyOTVw" points="[-42, -4, 445, 35]$[-427, -40, 60, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_i1nmUHJ5EfGBPZMgfyOTVw" id="(1.0,0.6046511627906976)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
