<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_f4iDEB4XEfG_jsm1Ob_k5A" name="MyDiagram" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_f4iqIB4XEfG_jsm1Ob_k5A" name="Atendimento Clínica Olho">
      <elements xmi:type="process:Lane" xmi:id="_f4iqIR4XEfG_jsm1Ob_k5A" name="Recepcionista" actor="_QyYG0FPOEfG9dLD7G3QBDg">
        <elements xmi:type="process:StartEvent" xmi:id="_f4iqIh4XEfG_jsm1Ob_k5A" name="Iniciar1" outgoing="_bh6rUFPREfG9dLD7G3QBDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f4iqIx4XEfG_jsm1Ob_k5A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f4iqJB4XEfG_jsm1Ob_k5A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f4iqJR4XEfG_jsm1Ob_k5A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_M-r18FPSEfG9dLD7G3QBDg" name="gateway padrão" outgoing="_R1S_kFPSEfG9dLD7G3QBDg" incoming="_Gh28cFPSEfG9dLD7G3QBDg _IfUHoFPSEfG9dLD7G3QBDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GhkBgFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GhizYFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GhkokFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_gAK38FPUEfG9dLD7G3QBDg" name="possui cadastro?" outgoing="_rjkxEFPREfG9dLD7G3QBDg _9BqYkFPREfG9dLD7G3QBDg" incoming="_bh6rUFPREfG9dLD7G3QBDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bhMSkFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bhLEcFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bhM5oFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_xvtb0FPUEfG9dLD7G3QBDg" name="forma de pagamento?" outgoing="_ZoTo4FPSEfG9dLD7G3QBDg _tDF7sFPUEfG9dLD7G3QBDg" incoming="_R1S_kFPSEfG9dLD7G3QBDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_R1AEoVPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_R1AEoFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_R1AEolPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_zt3xoFPUEfG9dLD7G3QBDg" name="gateway padão" outgoing="_EAUfwFfjEfGaAKjg7KE34A" incoming="_tDF7sFPUEfG9dLD7G3QBDg _lp86oF-rEfGJm-VfRlIdsQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_R2fngVPUEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_R2fngFPUEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_R2fnglPUEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_6SE50FfXEfGaAKjg7KE34A" name="agendado?" outgoing="_Kz_L8FfjEfGaAKjg7KE34A _Oxlp8FfjEfGaAKjg7KE34A" incoming="_EAUfwFfjEfGaAKjg7KE34A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6SJLQFfXEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6SIkMFfXEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6SJLQVfXEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_X5NSIF-sEfGJm-VfRlIdsQ" name="End1" incoming="_X5yg8F-sEfGJm-VfRlIdsQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_X5SKoF-sEfGJm-VfRlIdsQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_X5RjkF-sEfGJm-VfRlIdsQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_X5SKoV-sEfGJm-VfRlIdsQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_dCIDsGOREfGaD418Sxm7uA" name="tipo de serviço?" outgoing="_lmwD0FfjEfGaAKjg7KE34A _0w-LQFfjEfGaAKjg7KE34A _5yIWQGOPEfGaD418Sxm7uA" incoming="_Kz_L8FfjEfGaAKjg7KE34A _HBoLgGOSEfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KzuGMVfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KzuGMFfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KzuGMlfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ec3jYGOREfGaD418Sxm7uA" name="exame ou procedimento?" outgoing="_A7AfMFfkEfGaAKjg7KE34A _lPn7gGOPEfGaD418Sxm7uA" incoming="_0w-LQFfjEfGaAKjg7KE34A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0wvhwVfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0wvhwFfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0wvhwlfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_gqhGsGOREfGaD418Sxm7uA" name="gateway padrão" outgoing="_bxCPQGOREfGaD418Sxm7uA" incoming="_PXjxIGOREfGaD418Sxm7uA _aLIzAGOSEfGaD418Sxm7uA _by5bAGOSEfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PXF3EWOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PXF3EGOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PXGeIGOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ofCy8GOREfGaD418Sxm7uA" name="precisa realizar outro serviço?" outgoing="_sAv_IGOREfGaD418Sxm7uA _BcUI0GOSEfGaD418Sxm7uA" incoming="_bxCPQGOREfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_bwv7YGOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_bwvUUGOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_bwv7YWOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_sAeSUGOREfGaD418Sxm7uA" name="End3" incoming="_sAv_IGOREfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sAhVoWOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sAhVoGOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sAhVomOREfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_B47zYGOSEfGaD418Sxm7uA" name="lente de contato?" outgoing="_HBoLgGOSEfGaD418Sxm7uA _jwDNkGnOEfGG3LJZ6zip9w" incoming="_BcUI0GOSEfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BcOpQWOSEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BcOpQGOSEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BcOpQmOSEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_TnZZMGOSEfGaD418Sxm7uA" name="Autorizar serviço com operadora de saúde" outgoing="_SEnSwF-rEfGJm-VfRlIdsQ" incoming="_ZoTo4FPSEfG9dLD7G3QBDg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Zn4LEFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Zn3kAFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Zn4yIFPSEfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Zn4yIVPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Zn4yIlPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Zn4yI1PSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Zn4yJVPSEfG9dLD7G3QBDg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Zn4yJFPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_JGETAGOTEfGaD418Sxm7uA" name="Cadastrar paciente" outgoing="_Gh28cFPSEfG9dLD7G3QBDg" incoming="_9BqYkFPREfG9dLD7G3QBDg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9BR-EVPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9BR-EFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9BR-ElPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9BR-E1PREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9BR-FFPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9BR-FVPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9BR-F1PREfG9dLD7G3QBDg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9BR-FlPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_JGGIOGOTEfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_JGGIOWOTEfGaD418Sxm7uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_JGGIN2OTEfGaD418Sxm7uA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_JGGIOmOTEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_J4ywcGOTEfGaD418Sxm7uA" name="Anexar senha de autorização no sistema" outgoing="_lp86oF-rEfGJm-VfRlIdsQ" incoming="_SEnSwF-rEfGJm-VfRlIdsQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SEGVYV-rEfGJm-VfRlIdsQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SEGVYF-rEfGJm-VfRlIdsQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SEG8cF-rEfGJm-VfRlIdsQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SEG8cV-rEfGJm-VfRlIdsQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SEG8cl-rEfGJm-VfRlIdsQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SEG8c1-rEfGJm-VfRlIdsQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SEG8dV-rEfGJm-VfRlIdsQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SEG8dF-rEfGJm-VfRlIdsQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_J41zyGOTEfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_J41zyWOTEfGaD418Sxm7uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_J41zx2OTEfGaD418Sxm7uA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_J41zymOTEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5MLHYGUtEfGEXrYvpS-i_A" name="Confirmar ou atualizar cadastro" outgoing="_IfUHoFPSEfG9dLD7G3QBDg" incoming="_rjkxEFPREfG9dLD7G3QBDg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rjKhYFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rjJ6UFPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rjKhYVPREfG9dLD7G3QBDg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rjKhYlPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rjKhY1PREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rjKhZFPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rjKhZlPREfG9dLD7G3QBDg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rjKhZVPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5MM8mWUtEfGEXrYvpS-i_A">
            <targetForm xmi:type="expression:Expression" xmi:id="_5MM8mmUtEfGEXrYvpS-i_A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5MM8mGUtEfGEXrYvpS-i_A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5MM8m2UtEfGEXrYvpS-i_A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_topqYGnOEfGG3LJZ6zip9w" name="Agendar serviço" outgoing="_X5yg8F-sEfGJm-VfRlIdsQ" incoming="_Oxlp8FfjEfGaAKjg7KE34A _jwDNkGnOEfGG3LJZ6zip9w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_torfkWnOEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_torfkGnOEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_torfkmnOEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_torflWnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_torflmnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_torfl2nOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_torfmWnOEfGG3LJZ6zip9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_torfmGnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_tot70GnOEfGG3LJZ6zip9w" name="Agendar serviço" content="Agendar serviço" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_torflGnOEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_k2ts8B4aEfG2S7DpaDzKGg" name="Médico(a)">
        <elements xmi:type="process:Task" xmi:id="_ULXJQGOPEfGaD418Sxm7uA" name="Realizar procedimento" outgoing="_PXjxIGOREfGaD418Sxm7uA" incoming="_A7AfMFfkEfGaAKjg7KE34A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A6wAgVfkEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A6wAgFfkEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A6wAglfkEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_A6wAg1fkEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_A6wAhFfkEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_A6wAhVfkEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_A6wAh1fkEfGaAKjg7KE34A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_A6wAhlfkEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ULnA52OPEfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_ULnA6GOPEfGaD418Sxm7uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ULnA5mOPEfGaD418Sxm7uA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ULnn8GOPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Jwk6gGOREfGaD418Sxm7uA" name="Realizar consulta" outgoing="_by5bAGOSEfGaD418Sxm7uA" incoming="_gWRKcGOQEfGaD418Sxm7uA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gWDvEWOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gWDvEGOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gWDvEmOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_gWDvE2OQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_gWDvFGOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_gWDvFWOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_gWDvF2OQEfGaD418Sxm7uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_gWDvFmOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_JwmvuWOREfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_JwmvumOREfGaD418Sxm7uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_JwmvuGOREfGaD418Sxm7uA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Jwmvu2OREfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_lLRnsB4aEfG2S7DpaDzKGg" name="Equipe pré-consulta" actor="_5TtksGUrEfGEXrYvpS-i_A">
        <elements xmi:type="process:Task" xmi:id="_3IDTwF-sEfGJm-VfRlIdsQ" name="Realizar pré-consulta" outgoing="_gWRKcGOQEfGaD418Sxm7uA" incoming="_lmwD0FfjEfGaAKjg7KE34A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lmp9MlfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lmp9MVfjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lmp9M1fjEfGaAKjg7KE34A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lmp9NFfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lmp9NVfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lmp9NlfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lmp9OFfjEfGaAKjg7KE34A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lmp9N1fjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_3IJaZl-sEfGJm-VfRlIdsQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_3IJaZ1-sEfGJm-VfRlIdsQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_3IJaZV-sEfGJm-VfRlIdsQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_3IKBcF-sEfGJm-VfRlIdsQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_KkU7sF-sEfGJm-VfRlIdsQ" name="Técnico(a) de saúde" actor="_819jcGUrEfGEXrYvpS-i_A">
        <elements xmi:type="process:Task" xmi:id="_KOY34GOREfGaD418Sxm7uA" name="Realizar exame" outgoing="_aLIzAGOSEfGaD418Sxm7uA" incoming="_lPn7gGOPEfGaD418Sxm7uA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lPTycGOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lPTLYGOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lPTycWOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lPTycmOPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lPTyc2OPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lPTydGOPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lPTydmOPEfGaD418Sxm7uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lPTydWOPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_KOeXeGOREfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_KOeXeWOREfGaD418Sxm7uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_KOeXd2OREfGaD418Sxm7uA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_KOeXemOREfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_kFheAF-sEfGJm-VfRlIdsQ" name="Venda de lentes" actor="_JTFLcGUsEfGEXrYvpS-i_A">
        <elements xmi:type="process:EndEvent" xmi:id="_YkOxgGOQEfGaD418Sxm7uA" name="End2" incoming="_Yk-_cGOQEfGaD418Sxm7uA _aMnEkGOQEfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YkWGQWOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YkWGQGOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YkWGQmOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_eZxokGOQEfGaD418Sxm7uA" name="possui guia?" outgoing="_VEwZ8GOQEfGaD418Sxm7uA _aMnEkGOQEfGaD418Sxm7uA" incoming="_5yIWQGOPEfGaD418Sxm7uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5xv7wGOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5xvUsGOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5xv7wWOPEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_NLOxkGOTEfGaD418Sxm7uA" name="Realizar venda" outgoing="_Yk-_cGOQEfGaD418Sxm7uA" incoming="_VEwZ8GOQEfGaD418Sxm7uA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VEWxUGOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VEVjMGOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VEWxUWOQEfGaD418Sxm7uA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VEWxUmOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VEWxU2OQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VEWxVGOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VEWxVmOQEfGaD418Sxm7uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VEWxVWOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_NLP_uWOTEfGaD418Sxm7uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_NLP_umOTEfGaD418Sxm7uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_NLP_uGOTEfGaD418Sxm7uA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_NLQmwGOTEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_f4iqMx4XEfG_jsm1Ob_k5A">
        <targetForm xmi:type="expression:Expression" xmi:id="_f4iqNB4XEfG_jsm1Ob_k5A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_f4iqNR4XEfG_jsm1Ob_k5A">
        <targetForm xmi:type="expression:Expression" xmi:id="_f4iqNh4XEfG_jsm1Ob_k5A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bh6rUFPREfG9dLD7G3QBDg" target="_gAK38FPUEfG9dLD7G3QBDg" source="_f4iqIh4XEfG_jsm1Ob_k5A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bh9HkFPREfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_bh9HkVPREfG9dLD7G3QBDg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rjkxEFPREfG9dLD7G3QBDg" name="sim" target="_5MLHYGUtEfGEXrYvpS-i_A" source="_gAK38FPUEfG9dLD7G3QBDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rjlYIFPREfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_rjlYIVPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9BqYkFPREfG9dLD7G3QBDg" name="não" target="_JGETAGOTEfGaD418Sxm7uA" source="_gAK38FPUEfG9dLD7G3QBDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_9BrmsFPREfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_9BsNwFPREfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Gh28cFPSEfG9dLD7G3QBDg" target="_M-r18FPSEfG9dLD7G3QBDg" source="_JGETAGOTEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Gh3jgFPSEfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Gh3jgVPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IfUHoFPSEfG9dLD7G3QBDg" target="_M-r18FPSEfG9dLD7G3QBDg" source="_5MLHYGUtEfGEXrYvpS-i_A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IfVVwFPSEfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_IfWj4FPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_R1S_kFPSEfG9dLD7G3QBDg" target="_xvtb0FPUEfG9dLD7G3QBDg" source="_M-r18FPSEfG9dLD7G3QBDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_R1S_kVPSEfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_R1TmoFPSEfG9dLD7G3QBDg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZoTo4FPSEfG9dLD7G3QBDg" name="plano" target="_TnZZMGOSEfGaD418Sxm7uA" source="_xvtb0FPUEfG9dLD7G3QBDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZoUP8FPSEfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZoU3AFPSEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tDF7sFPUEfG9dLD7G3QBDg" name="particular" target="_zt3xoFPUEfG9dLD7G3QBDg" source="_xvtb0FPUEfG9dLD7G3QBDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tDHw4FPUEfG9dLD7G3QBDg"/>
        <condition xmi:type="expression:Expression" xmi:id="_tDHw4VPUEfG9dLD7G3QBDg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EAUfwFfjEfGaAKjg7KE34A" target="_6SE50FfXEfGaAKjg7KE34A" source="_zt3xoFPUEfG9dLD7G3QBDg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EAYKIFfjEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_EAYKIVfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Kz_L8FfjEfGaAKjg7KE34A" name="sim" target="_dCIDsGOREfGaD418Sxm7uA" source="_6SE50FfXEfGaAKjg7KE34A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Kz_L8VfjEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_Kz_L8lfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Oxlp8FfjEfGaAKjg7KE34A" name="não" target="_topqYGnOEfGG3LJZ6zip9w" source="_6SE50FfXEfGaAKjg7KE34A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OxoGMFfjEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_OxotQFfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lmwD0FfjEfGaAKjg7KE34A" name="consulta/retorno" target="_3IDTwF-sEfGJm-VfRlIdsQ" source="_dCIDsGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lmwD0VfjEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_lmwD0lfjEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0w-LQFfjEfGaAKjg7KE34A" target="_ec3jYGOREfGaD418Sxm7uA" source="_dCIDsGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0w-LQVfjEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_0w-LQlfjEfGaAKjg7KE34A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_A7AfMFfkEfGaAKjg7KE34A" name="procedimento" target="_ULXJQGOPEfGaD418Sxm7uA" source="_ec3jYGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_A7BGQFfkEfGaAKjg7KE34A"/>
        <condition xmi:type="expression:Expression" xmi:id="_A7BGQVfkEfGaAKjg7KE34A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SEnSwF-rEfGJm-VfRlIdsQ" target="_J4ywcGOTEfGaD418Sxm7uA" source="_TnZZMGOSEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SEpvAF-rEfGJm-VfRlIdsQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_SEpvAV-rEfGJm-VfRlIdsQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lp86oF-rEfGJm-VfRlIdsQ" target="_zt3xoFPUEfG9dLD7G3QBDg" source="_J4ywcGOTEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lqBMEF-rEfGJm-VfRlIdsQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_lqCaMF-rEfGJm-VfRlIdsQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_X5yg8F-sEfGJm-VfRlIdsQ" target="_X5NSIF-sEfGJm-VfRlIdsQ" source="_topqYGnOEfGG3LJZ6zip9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_X5zIAF-sEfGJm-VfRlIdsQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_X5zIAV-sEfGJm-VfRlIdsQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lPn7gGOPEfGaD418Sxm7uA" name="exame" target="_KOY34GOREfGaD418Sxm7uA" source="_ec3jYGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lPoikGOPEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_lPoikWOPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5yIWQGOPEfGaD418Sxm7uA" name="venda de lente" target="_eZxokGOQEfGaD418Sxm7uA" source="_dCIDsGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5yI9UGOPEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_5yJkYGOPEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VEwZ8GOQEfGaD418Sxm7uA" name="sim" target="_NLOxkGOTEfGaD418Sxm7uA" source="_eZxokGOQEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VEyPIGOQEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_VEyPIWOQEfGaD418Sxm7uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Yk-_cGOQEfGaD418Sxm7uA" target="_YkOxgGOQEfGaD418Sxm7uA" source="_NLOxkGOTEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Yk-_cWOQEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Yk_mgGOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aMnEkGOQEfGaD418Sxm7uA" name="não" target="_YkOxgGOQEfGaD418Sxm7uA" source="_eZxokGOQEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aMnroGOQEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_aMnroWOQEfGaD418Sxm7uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gWRKcGOQEfGaD418Sxm7uA" target="_Jwk6gGOREfGaD418Sxm7uA" source="_3IDTwF-sEfGJm-VfRlIdsQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gWRxgGOQEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_gWRxgWOQEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PXjxIGOREfGaD418Sxm7uA" target="_gqhGsGOREfGaD418Sxm7uA" source="_ULXJQGOPEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PXkYMGOREfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_PXkYMWOREfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_bxCPQGOREfGaD418Sxm7uA" target="_ofCy8GOREfGaD418Sxm7uA" source="_gqhGsGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_bxCPQWOREfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_bxCPQmOREfGaD418Sxm7uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sAv_IGOREfGaD418Sxm7uA" name="não" target="_sAeSUGOREfGaD418Sxm7uA" source="_ofCy8GOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sAv_IWOREfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_sAv_ImOREfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BcUI0GOSEfGaD418Sxm7uA" name="sim" target="_B47zYGOSEfGaD418Sxm7uA" source="_ofCy8GOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BcUI0WOSEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BcUI0mOSEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HBoLgGOSEfGaD418Sxm7uA" name="sim" target="_dCIDsGOREfGaD418Sxm7uA" source="_B47zYGOSEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HBr14GOSEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_HBr14WOSEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aLIzAGOSEfGaD418Sxm7uA" target="_gqhGsGOREfGaD418Sxm7uA" source="_KOY34GOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aLKBIGOSEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_aLKBIWOSEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_by5bAGOSEfGaD418Sxm7uA" target="_gqhGsGOREfGaD418Sxm7uA" source="_Jwk6gGOREfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_by6CEGOSEfGaD418Sxm7uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_by6CEWOSEfGaD418Sxm7uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jwDNkGnOEfGG3LJZ6zip9w" name="não" target="_topqYGnOEfGG3LJZ6zip9w" source="_B47zYGOSEfGaD418Sxm7uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jwR3EGnOEfGG3LJZ6zip9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_jwTsQGnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_QyYG0FPOEfG9dLD7G3QBDg" documentation="Funcionário(a) que trabalha na recepção, responsável pelo atendimento e agendamento" name="Recepcionista" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_xFzCwGRUEfG-37a2zyZkMg" documentation="Funcionário(a) que trabalha no corpo clínico, responsável pela" name="Médico"/>
      <actors xmi:type="process:Actor" xmi:id="_5TtksGUrEfGEXrYvpS-i_A" name="Atendente de pré-consulta"/>
      <actors xmi:type="process:Actor" xmi:id="_819jcGUrEfGEXrYvpS-i_A" name="Técnico de saúde"/>
      <actors xmi:type="process:Actor" xmi:id="_JTFLcGUsEfGEXrYvpS-i_A" name="Recepcionista (venda de lentes)"/>
      <contract xmi:type="process:Contract" xmi:id="_f4iqOx4XEfG_jsm1Ob_k5A"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f4jRMB4XEfG_jsm1Ob_k5A">
        <name xmi:type="expression:Expression" xmi:id="_f4jRMR4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f4jRMh4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f4jRMx4XEfG_jsm1Ob_k5A">
        <name xmi:type="expression:Expression" xmi:id="_f4jRNB4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f4jRNR4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f4jRNh4XEfG_jsm1Ob_k5A">
        <name xmi:type="expression:Expression" xmi:id="_f4jRNx4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f4jROB4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f4jROR4XEfG_jsm1Ob_k5A">
        <name xmi:type="expression:Expression" xmi:id="_f4jROh4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f4jROx4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_f4jRPB4XEfG_jsm1Ob_k5A">
        <name xmi:type="expression:Expression" xmi:id="_f4jRPR4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_f4jRPh4XEfG_jsm1Ob_k5A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_tmfuQGnOEfGG3LJZ6zip9w" name="Agendar serviço">
      <elements xmi:type="process:Task" xmi:id="_tpwdoWnOEfGG3LJZ6zip9w" name="Copy of Agendar serviço" incoming="_8WjMwGnPEfGG3LJZ6zip9w" actor="_tpwdoGnOEfGG3LJZ6zip9w">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_tpwdomnOEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_tpwdo2nOEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_tpwdpGnOEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_tpwdpWnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_tpwdpmnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tpwdp2nOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_tpwdqGnOEfGG3LJZ6zip9w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_tpwdqWnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_tpwdqmnOEfGG3LJZ6zip9w">
          <targetForm xmi:type="expression:Expression" xmi:id="_tpwdq2nOEfGG3LJZ6zip9w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_tpwdrGnOEfGG3LJZ6zip9w"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_tpwdrWnOEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:StartEvent" xmi:id="_0_36IGnPEfGG3LJZ6zip9w" name="Start1" outgoing="_2FbM8GnPEfGG3LJZ6zip9w">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_1ADgUGnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_1AC5QGnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_1ADgUWnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_2hRbcGnPEfGG3LJZ6zip9w" name="Gateway padrão" outgoing="_402noGnPEfGG3LJZ6zip9w" incoming="_2FbM8GnPEfGG3LJZ6zip9w">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_2E_IEGnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_2E-hAGnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_2E_IEWnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_6EMIkGnPEfGG3LJZ6zip9w" name="tipo de serviço?" outgoing="_8WjMwGnPEfGG3LJZ6zip9w _EDjUsGnQEfGG3LJZ6zip9w" incoming="_402noGnPEfGG3LJZ6zip9w">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_40lh4WnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_40lh4GnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_40mI8GnPEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ANDGateway" xmi:id="_EDQZwGnQEfGG3LJZ6zip9w" name="Gateway1" incoming="_EDjUsGnQEfGG3LJZ6zip9w">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_EDS2AWnQEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_EDS2AGnQEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_EDS2AmnQEfGG3LJZ6zip9w" name="" content="" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_toggcGnOEfGG3LJZ6zip9w" type="NONE">
        <targetForm xmi:type="expression:Expression" xmi:id="_toggcWnOEfGG3LJZ6zip9w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_toggcmnOEfGG3LJZ6zip9w">
        <targetForm xmi:type="expression:Expression" xmi:id="_toggc2nOEfGG3LJZ6zip9w" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2FbM8GnPEfGG3LJZ6zip9w" target="_2hRbcGnPEfGG3LJZ6zip9w" source="_0_36IGnPEfGG3LJZ6zip9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2Fb0AGnPEfGG3LJZ6zip9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_2FcbEGnPEfGG3LJZ6zip9w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_402noGnPEfGG3LJZ6zip9w" target="_6EMIkGnPEfGG3LJZ6zip9w" source="_2hRbcGnPEfGG3LJZ6zip9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_403OsGnPEfGG3LJZ6zip9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_403OsWnPEfGG3LJZ6zip9w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8WjMwGnPEfGG3LJZ6zip9w" name="cirurgia" target="_tpwdoWnOEfGG3LJZ6zip9w" source="_6EMIkGnPEfGG3LJZ6zip9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8Wjz0GnPEfGG3LJZ6zip9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_8Wjz0WnPEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EDjUsGnQEfGG3LJZ6zip9w" name="consulta/procedimento/exame" target="_EDQZwGnQEfGG3LJZ6zip9w" source="_6EMIkGnPEfGG3LJZ6zip9w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EDj7wGnQEfGG3LJZ6zip9w"/>
        <condition xmi:type="expression:Expression" xmi:id="_EDj7wWnQEfGG3LJZ6zip9w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_tpwdoGnOEfGG3LJZ6zip9w" documentation="Funcionário(a) que trabalha na recepção, responsável pelo atendimento e agendamento" name="Recepcionista"/>
      <contract xmi:type="process:Contract" xmi:id="_tohukGnOEfGG3LJZ6zip9w"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_toerQGnOEfGG3LJZ6zip9w">
        <name xmi:type="expression:Expression" xmi:id="_tofSUGnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tof5YGnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tof5YWnOEfGG3LJZ6zip9w">
        <name xmi:type="expression:Expression" xmi:id="_tof5YmnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tof5Y2nOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tof5ZGnOEfGG3LJZ6zip9w">
        <name xmi:type="expression:Expression" xmi:id="_tof5ZWnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tof5ZmnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tof5Z2nOEfGG3LJZ6zip9w">
        <name xmi:type="expression:Expression" xmi:id="_tof5aGnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tof5aWnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_tof5amnOEfGG3LJZ6zip9w">
        <name xmi:type="expression:Expression" xmi:id="_tof5a2nOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_tof5bGnOEfGG3LJZ6zip9w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_f4jRPx4XEfG_jsm1Ob_k5A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_f4jRQB4XEfG_jsm1Ob_k5A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_f4jRQR4XEfG_jsm1Ob_k5A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_f4jRQh4XEfG_jsm1Ob_k5A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_f4jRQx4XEfG_jsm1Ob_k5A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_f4jRRB4XEfG_jsm1Ob_k5A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_f4jRRR4XEfG_jsm1Ob_k5A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_f4jRRh4XEfG_jsm1Ob_k5A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_f4jRRx4XEfG_jsm1Ob_k5A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_f4j4QB4XEfG_jsm1Ob_k5A" type="Process" element="_f4iDEB4XEfG_jsm1Ob_k5A" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_f4kfUB4XEfG_jsm1Ob_k5A" type="2007" element="_f4iqIB4XEfG_jsm1Ob_k5A">
      <children xmi:type="notation:DecorationNode" xmi:id="_f4kfUR4XEfG_jsm1Ob_k5A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_f4kfUh4XEfG_jsm1Ob_k5A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_f4kfUx4XEfG_jsm1Ob_k5A" type="3007" element="_f4iqIR4XEfG_jsm1Ob_k5A">
          <children xmi:type="notation:DecorationNode" xmi:id="_f4kfVB4XEfG_jsm1Ob_k5A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_f4kfVR4XEfG_jsm1Ob_k5A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_f4kfWR4XEfG_jsm1Ob_k5A" type="3002" element="_f4iqIh4XEfG_jsm1Ob_k5A" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_f4kfWh4XEfG_jsm1Ob_k5A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_f4kfWx4XEfG_jsm1Ob_k5A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f4kfXB4XEfG_jsm1Ob_k5A" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_M-xVgFPSEfG9dLD7G3QBDg" type="3008" element="_M-r18FPSEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_M-xVglPSEfG9dLD7G3QBDg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_M-x8kFPSEfG9dLD7G3QBDg" x="1" y="8"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_M-xVgVPSEfG9dLD7G3QBDg" x="438" y="106" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gAOiUFPUEfG9dLD7G3QBDg" type="3008" element="_gAK38FPUEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_gAPwcFPUEfG9dLD7G3QBDg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gAPwcVPUEfG9dLD7G3QBDg" y="-63"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gAOiUVPUEfG9dLD7G3QBDg" x="147" y="60" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xvv4EFPUEfG9dLD7G3QBDg" type="3008" element="_xvtb0FPUEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_xvxGMFPUEfG9dLD7G3QBDg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_xvxGMVPUEfG9dLD7G3QBDg" x="1" y="-58"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xvv4EVPUEfG9dLD7G3QBDg" x="539" y="107" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zt4_w1PUEfG9dLD7G3QBDg" type="3008" element="_zt3xoFPUEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_zt4_xVPUEfG9dLD7G3QBDg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_zt5m0FPUEfG9dLD7G3QBDg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zt4_xFPUEfG9dLD7G3QBDg" x="721" y="292" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6SSVMFfXEfGaAKjg7KE34A" type="3008" element="_6SE50FfXEfGaAKjg7KE34A" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_6SUxcFfXEfGaAKjg7KE34A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6SUxcVfXEfGaAKjg7KE34A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6SS8QFfXEfGaAKjg7KE34A" x="819" y="292"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_X5atgF-sEfGJm-VfRlIdsQ" type="3003" element="_X5NSIF-sEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_X5b7oF-sEfGJm-VfRlIdsQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_X5dJwF-sEfGJm-VfRlIdsQ" x="34" y="-16"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_X5atgV-sEfGJm-VfRlIdsQ" x="970" y="28"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dCKf8GOREfGaD418Sxm7uA" type="3008" element="_dCIDsGOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_dCKf8mOREfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dCKf82OREfGaD418Sxm7uA" y="-64"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dCKf8WOREfGaD418Sxm7uA" x="994" y="292" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ec7NwGOREfGaD418Sxm7uA" type="3008" element="_ec3jYGOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_ec700GOREfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ec700WOREfGaD418Sxm7uA" y="-55"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ec7NwWOREfGaD418Sxm7uA" x="1121" y="293" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gql_MGOREfGaD418Sxm7uA" type="3008" element="_gqhGsGOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_gqn0YGOREfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gqobcGOREfGaD418Sxm7uA" x="-64" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gql_MWOREfGaD418Sxm7uA" x="1432" y="329" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ofHrcGOREfGaD418Sxm7uA" type="3008" element="_ofCy8GOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_ofISgGOREfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ofI5kGOREfGaD418Sxm7uA" x="-89" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ofHrcWOREfGaD418Sxm7uA" x="1432" y="234" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sAjx4GOREfGaD418Sxm7uA" type="3003" element="_sAeSUGOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_sAlAAGOREfGaD418Sxm7uA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sAlAAWOREfGaD418Sxm7uA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sAjx4WOREfGaD418Sxm7uA" x="1564" y="243"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_B4-2sGOSEfGaD418Sxm7uA" type="3008" element="_B47zYGOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_B5Ar4GOSEfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_B5BS8GOSEfGaD418Sxm7uA" y="-60"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_B4-2sWOSEfGaD418Sxm7uA" x="1431" y="146" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Tnb1cGOSEfGaD418Sxm7uA" type="3027" element="_TnZZMGOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TndDkGOSEfGaD418Sxm7uA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Tnb1cWOSEfGaD418Sxm7uA" x="666" y="35" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_JGGvQGOTEfGaD418Sxm7uA" type="3005" element="_JGETAGOTEfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JGH9YGOTEfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JGGvQWOTEfGaD418Sxm7uA" x="239" y="152" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_J42a0GOTEfGaD418Sxm7uA" type="3005" element="_J4ywcGOTEfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_J43B4GOTEfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_J42a0WOTEfGaD418Sxm7uA" x="671" y="162" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5MNjoGUtEfGEXrYvpS-i_A" type="3005" element="_5MLHYGUtEfGEXrYvpS-i_A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5MP_4GUtEfGEXrYvpS-i_A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5MNjoWUtEfGEXrYvpS-i_A" x="231" y="57" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tostsGnOEfGG3LJZ6zip9w" type="3063" element="_topqYGnOEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tostsmnOEfGG3LJZ6zip9w" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tostsWnOEfGG3LJZ6zip9w" x="927" y="103" width="116" height="58"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_f4kfXR4XEfG_jsm1Ob_k5A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_f4kfXh4XEfG_jsm1Ob_k5A" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_f4kfXx4XEfG_jsm1Ob_k5A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_f4kfYB4XEfG_jsm1Ob_k5A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f4kfYR4XEfG_jsm1Ob_k5A" x="19" y="10" width="1697" height="434"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_k29kkB4aEfG2S7DpaDzKGg" type="3007" element="_k2ts8B4aEfG2S7DpaDzKGg">
          <children xmi:type="notation:DecorationNode" xmi:id="_k3BO8B4aEfG2S7DpaDzKGg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_k3BO8R4aEfG2S7DpaDzKGg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_ULxY8GOPEfGaD418Sxm7uA" type="3005" element="_ULXJQGOPEfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ULz1MGOPEfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ULyAAGOPEfGaD418Sxm7uA" x="1211" y="38" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Jwok4GOREfGaD418Sxm7uA" type="3005" element="_Jwk6gGOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_JwqaEGOREfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Jwok4WOREfGaD418Sxm7uA" x="666" y="104" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_k2-LoB4aEfG2S7DpaDzKGg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_k2-LoR4aEfG2S7DpaDzKGg" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_k2-Loh4aEfG2S7DpaDzKGg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_k3BO8h4aEfG2S7DpaDzKGg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_k2-Lox4aEfG2S7DpaDzKGg" x="19" y="398" width="1697" height="203"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_lLUD8B4aEfG2S7DpaDzKGg" type="3007" element="_lLRnsB4aEfG2S7DpaDzKGg">
          <children xmi:type="notation:DecorationNode" xmi:id="_lLV5IB4aEfG2S7DpaDzKGg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_lLV5IR4aEfG2S7DpaDzKGg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_3IMdsF-sEfGJm-VfRlIdsQ" type="3005" element="_3IDTwF-sEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3IQIEF-sEfGJm-VfRlIdsQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3IMdsV-sEfGJm-VfRlIdsQ" x="189" y="58" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_lLUD8R4aEfG2S7DpaDzKGg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_lLUD8h4aEfG2S7DpaDzKGg" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_lLUD8x4aEfG2S7DpaDzKGg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_lLV5Ih4aEfG2S7DpaDzKGg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lLUD9B4aEfG2S7DpaDzKGg" x="19" y="629" width="1697" height="175"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_KkbpYF-sEfGJm-VfRlIdsQ" type="3007" element="_KkU7sF-sEfGJm-VfRlIdsQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_KkcQcF-sEfGJm-VfRlIdsQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_KkcQcV-sEfGJm-VfRlIdsQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_KOgMoGOREfGaD418Sxm7uA" type="3005" element="_KOY34GOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KOgzsGOREfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KOgMoWOREfGaD418Sxm7uA" x="791" y="63" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_KkbpYV-sEfGJm-VfRlIdsQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_KkbpYl-sEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_KkbpY1-sEfGJm-VfRlIdsQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_KkcQcl-sEfGJm-VfRlIdsQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KkbpZF-sEfGJm-VfRlIdsQ" x="19" y="776" width="1697" height="175"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_kFj6QF-sEfGJm-VfRlIdsQ" type="3007" element="_kFheAF-sEfGJm-VfRlIdsQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_kFkhUF-sEfGJm-VfRlIdsQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_kFlIYF-sEfGJm-VfRlIdsQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Ykmk8GOQEfGaD418Sxm7uA" type="3003" element="_YkOxgGOQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_YknzEGOQEfGaD418Sxm7uA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_YknzEWOQEfGaD418Sxm7uA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ykmk8WOQEfGaD418Sxm7uA" x="170" y="158"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eZ0r4GOQEfGaD418Sxm7uA" type="3008" element="_eZxokGOQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_eZ1S8GOQEfGaD418Sxm7uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_eZ1S8WOQEfGaD418Sxm7uA" x="-50" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eZ0r4WOQEfGaD418Sxm7uA" x="91" y="62" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NLTDAGOTEfGaD418Sxm7uA" type="3005" element="_NLOxkGOTEfGaD418Sxm7uA" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NLTDAmOTEfGaD418Sxm7uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NLTDAWOTEfGaD418Sxm7uA" x="209" y="59" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_kFj6QV-sEfGJm-VfRlIdsQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_kFj6Ql-sEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_kFj6Q1-sEfGJm-VfRlIdsQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_kFlvcF-sEfGJm-VfRlIdsQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kFj6RF-sEfGJm-VfRlIdsQ" x="44" y="987" width="1807" height="230"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_f4kfYh4XEfG_jsm1Ob_k5A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_f4kfYx4XEfG_jsm1Ob_k5A" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_f4kfZB4XEfG_jsm1Ob_k5A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_f4kfZR4XEfG_jsm1Ob_k5A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f4kfZh4XEfG_jsm1Ob_k5A" width="1826" height="278"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_tokx4GnOEfGG3LJZ6zip9w" type="2007" element="_tmfuQGnOEfGG3LJZ6zip9w">
      <children xmi:type="notation:DecorationNode" xmi:id="_ton1MGnOEfGG3LJZ6zip9w" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_ton1MWnOEfGG3LJZ6zip9w" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_tpzg8GnOEfGG3LJZ6zip9w" type="3005" element="_tpwdoWnOEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_tp0IAGnOEfGG3LJZ6zip9w" type="5005" element="_tpwdoWnOEfGG3LJZ6zip9w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tp0IAWnOEfGG3LJZ6zip9w" x="291" y="203" width="132" height="66"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_1ANRUGnPEfGG3LJZ6zip9w" type="3002" element="_0_36IGnPEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_1AQUoGnPEfGG3LJZ6zip9w" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_1AQ7sGnPEfGG3LJZ6zip9w" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1AN4YGnPEfGG3LJZ6zip9w" x="92" y="92"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_2halYGnPEfGG3LJZ6zip9w" type="3008" element="_2hRbcGnPEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_2hdosGnPEfGG3LJZ6zip9w" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_2hdosWnPEfGG3LJZ6zip9w" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2hbMcGnPEfGG3LJZ6zip9w" x="191" y="88" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_6EQaAGnPEfGG3LJZ6zip9w" type="3008" element="_6EMIkGnPEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_6ERBEGnPEfGG3LJZ6zip9w" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_6ERBEWnPEfGG3LJZ6zip9w" y="-63"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6EQaAWnPEfGG3LJZ6zip9w" x="335" y="88" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_EDWgYGnQEfGG3LJZ6zip9w" type="3009" element="_EDQZwGnQEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_EDXugGnQEfGG3LJZ6zip9w" type="5020">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_EDXugWnQEfGG3LJZ6zip9w" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EDWgYWnQEfGG3LJZ6zip9w" x="572" y="90"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_tolY8GnOEfGG3LJZ6zip9w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_tomAAGnOEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_tomAAWnOEfGG3LJZ6zip9w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_ton1MmnOEfGG3LJZ6zip9w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tomAAmnOEfGG3LJZ6zip9w" width="1886" height="316"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_f4kfZx4XEfG_jsm1Ob_k5A"/>
    <edges xmi:type="notation:Connector" xmi:id="_bh_j0FPREfG9dLD7G3QBDg" type="4001" element="_bh6rUFPREfG9dLD7G3QBDg" source="_f4kfWR4XEfG_jsm1Ob_k5A" target="_gAOiUFPUEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_biAK4FPREfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_biAK4VPREfG9dLD7G3QBDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bh_j0VPREfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bh_j0lPREfG9dLD7G3QBDg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rjqQoFPREfG9dLD7G3QBDg" type="4001" element="_rjkxEFPREfG9dLD7G3QBDg" source="_gAOiUFPUEfG9dLD7G3QBDg" target="_5MNjoGUtEfGEXrYvpS-i_A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rjq3sFPREfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rjq3sVPREfG9dLD7G3QBDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rjqQoVPREfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rjqQolPREfG9dLD7G3QBDg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9B8FYFPREfG9dLD7G3QBDg" type="4001" element="_9BqYkFPREfG9dLD7G3QBDg" source="_gAOiUFPUEfG9dLD7G3QBDg" target="_JGGvQGOTEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_9B8scFPREfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9B8scVPREfG9dLD7G3QBDg" x="-2" y="-16"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9B8FYVPREfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9B8FYlPREfG9dLD7G3QBDg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BrMIcFPSEfG9dLD7G3QBDg" id="(0.3488372093023256,0.8604651162790697)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ac8zsFPSEfG9dLD7G3QBDg" id="(0.08,0.78)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Gh6m0FPSEfG9dLD7G3QBDg" type="4001" element="_Gh28cFPSEfG9dLD7G3QBDg" source="_JGGvQGOTEfGaD418Sxm7uA" target="_M-xVgFPSEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Gh7N4FPSEfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Gh7N4VPSEfG9dLD7G3QBDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Gh6m0VPSEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Gh6m0lPSEfG9dLD7G3QBDg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HOziAFPSEfG9dLD7G3QBDg" id="(0.98,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IfZAIFPSEfG9dLD7G3QBDg" type="4001" element="_IfUHoFPSEfG9dLD7G3QBDg" source="_5MNjoGUtEfGEXrYvpS-i_A" target="_M-xVgFPSEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IfZnMFPSEfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IfaOQFPSEfG9dLD7G3QBDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IfZAIVPSEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IfZAIlPSEfG9dLD7G3QBDg" points="[0, 0, -108, -42]$[48, 0, -60, -42]$[48, 37, -60, -5]$[92, 37, -16, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IfgU4FPSEfG9dLD7G3QBDg" id="(1.0,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_R1U0wFPSEfG9dLD7G3QBDg" type="4001" element="_R1S_kFPSEfG9dLD7G3QBDg" source="_M-xVgFPSEfG9dLD7G3QBDg" target="_xvv4EFPUEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_R1WC4FPSEfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_R1WC4VPSEfG9dLD7G3QBDg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_R1U0wVPSEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_R1U0wlPSEfG9dLD7G3QBDg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZoWsMFPSEfG9dLD7G3QBDg" type="4001" element="_ZoTo4FPSEfG9dLD7G3QBDg" source="_xvv4EFPUEfG9dLD7G3QBDg" target="_Tnb1cGOSEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZoXTQFPSEfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZoXTQVPSEfG9dLD7G3QBDg" x="2" y="-29"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZoWsMVPSEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZoWsMlPSEfG9dLD7G3QBDg" points="[22, 0, -154, 58]$[90, 0, -86, 58]$[90, -63, -86, -5]$[106, -63, -70, -5]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tDJmEFPUEfG9dLD7G3QBDg" type="4001" element="_tDF7sFPUEfG9dLD7G3QBDg" source="_xvv4EFPUEfG9dLD7G3QBDg" target="_zt4_w1PUEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tDMCUFPUEfG9dLD7G3QBDg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tDMCUVPUEfG9dLD7G3QBDg" x="-75" y="-28"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tDJmEVPUEfG9dLD7G3QBDg" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tDJmElPUEfG9dLD7G3QBDg" points="[11, 16, -182, -163]$[11, 179, -182, 0]$[172, 179, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tDSwAFPUEfG9dLD7G3QBDg" id="(0.23255813953488372,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EAamYFfjEfGaAKjg7KE34A" type="4001" element="_EAUfwFfjEfGaAKjg7KE34A" source="_zt4_w1PUEfG9dLD7G3QBDg" target="_6SSVMFfXEfGaAKjg7KE34A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EAcbkFfjEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EAdCoFfjEfGaAKjg7KE34A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EAamYVfjEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EAamYlfjEfGaAKjg7KE34A" points="[-6, 0, -82, 6]$[75, 14, -1, 20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EAjJQFfjEfGaAKjg7KE34A" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_K0AaEFfjEfGaAKjg7KE34A" type="4001" element="_Kz_L8FfjEfGaAKjg7KE34A" source="_6SSVMFfXEfGaAKjg7KE34A" target="_dCKf8GOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_K0C2UFfjEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_K0DdYFfjEfGaAKjg7KE34A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_K0AaEVfjEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_K0AaElfjEfGaAKjg7KE34A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Ox7oMFfjEfGaAKjg7KE34A" type="4001" element="_Oxlp8FfjEfGaAKjg7KE34A" source="_6SSVMFfXEfGaAKjg7KE34A" target="_tostsGnOEfGG3LJZ6zip9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ox8PQFfjEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ox8PQVfjEfGaAKjg7KE34A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ox7oMVfjEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ox7oMlfjEfGaAKjg7KE34A" points="[-22, -30, -137, 164]$[-22, -114, -137, 80]$[114, -114, -1, 80]$[114, -169, -1, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OyAgsFfjEfGaAKjg7KE34A" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lmwD01fjEfGaAKjg7KE34A" type="4001" element="_lmwD0FfjEfGaAKjg7KE34A" source="_dCKf8GOREfGaD418Sxm7uA" target="_3IMdsF-sEfGJm-VfRlIdsQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lmwq4FfjEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lmwq4VfjEfGaAKjg7KE34A" x="184" y="-5"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lmwD1FfjEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lmwD1VfjEfGaAKjg7KE34A" points="[0, 22, 766, -390]$[0, 147, 766, -265]$[-757, 147, 9, -265]$[-757, 382, 9, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0w-yUFfjEfGaAKjg7KE34A" type="4001" element="_0w-LQFfjEfGaAKjg7KE34A" source="_dCKf8GOREfGaD418Sxm7uA" target="_ec7NwGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0w_ZYFfjEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0w_ZYVfjEfGaAKjg7KE34A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0w-yUVfjEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0w-yUlfjEfGaAKjg7KE34A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_A7BGQlfkEfGaAKjg7KE34A" type="4001" element="_A7AfMFfkEfGaAKjg7KE34A" source="_ec7NwGOREfGaD418Sxm7uA" target="_ULxY8GOPEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_A7BGRVfkEfGaAKjg7KE34A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_A7BGRlfkEfGaAKjg7KE34A" x="-16" y="54"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_A7BGQ1fkEfGaAKjg7KE34A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_A7BGRFfkEfGaAKjg7KE34A" points="[20, -1, -109, -189]$[125, -1, -4, -189]$[125, 158, -4, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SEtZYF-rEfGJm-VfRlIdsQ" type="4001" element="_SEnSwF-rEfGJm-VfRlIdsQ" source="_Tnb1cGOSEfGaD418Sxm7uA" target="_J42a0GOTEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SEungF-rEfGJm-VfRlIdsQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SEvOkF-rEfGJm-VfRlIdsQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SEtZYV-rEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SEtZYl-rEfGJm-VfRlIdsQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lqFdgF-rEfGJm-VfRlIdsQ" type="4001" element="_lp86oF-rEfGJm-VfRlIdsQ" source="_J42a0GOTEfGaD418Sxm7uA" target="_zt4_w1PUEfG9dLD7G3QBDg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lqH5wF-rEfGJm-VfRlIdsQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lqH5wV-rEfGJm-VfRlIdsQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lqGEkF-rEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lqGEkV-rEfGJm-VfRlIdsQ" points="[-69, 42, 0, -81]$[-69, 102, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lqOncF-rEfGJm-VfRlIdsQ" id="(1.0,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_X50WIF-sEfGJm-VfRlIdsQ" type="4001" element="_X5yg8F-sEfGJm-VfRlIdsQ" source="_tostsGnOEfGG3LJZ6zip9w" target="_X5atgF-sEfGJm-VfRlIdsQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_X50WI1-sEfGJm-VfRlIdsQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_X50WJF-sEfGJm-VfRlIdsQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_X50WIV-sEfGJm-VfRlIdsQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_X50WIl-sEfGJm-VfRlIdsQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lPpJoGOPEfGaD418Sxm7uA" type="4001" element="_lPn7gGOPEfGaD418Sxm7uA" source="_ec7NwGOREfGaD418Sxm7uA" target="_KOgMoGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lPq-0GOPEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lPq-0WOPEfGaD418Sxm7uA" x="-342" y="26"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lPpJoWOPEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lPpJomOPEfGaD418Sxm7uA" points="[-21, 33, 301, -564]$[-21, 493, 301, -104]$[-323, 493, -1, -104]$[-323, 572, -1, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_mdcZgGOPEfGaD418Sxm7uA" id="(0.9767441860465116,0.23255813953488372)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5yKLcGOPEfGaD418Sxm7uA" type="4001" element="_5yIWQGOPEfGaD418Sxm7uA" source="_dCKf8GOREfGaD418Sxm7uA" target="_eZ0r4GOQEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5yKygGOPEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5yKygWOPEfGaD418Sxm7uA" x="40" y="9"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5yKLcWOPEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5yKLcmOPEfGaD418Sxm7uA" points="[0, 22, 902, -724]$[0, 105, 902, -641]$[-896, 105, 6, -641]$[-896, 742, 6, -4]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__VAI8GOPEfGaD418Sxm7uA" id="(0.5116279069767442,0.23255813953488372)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VEyPImOQEfGaD418Sxm7uA" type="4001" element="_VEwZ8GOQEfGaD418Sxm7uA" source="_eZ0r4GOQEfGaD418Sxm7uA" target="_NLTDAGOTEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VEy2MmOQEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VEy2M2OQEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VEy2MGOQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VEy2MWOQEfGaD418Sxm7uA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YlA0oGOQEfGaD418Sxm7uA" type="4001" element="_Yk-_cGOQEfGaD418Sxm7uA" source="_NLTDAGOTEfGaD418Sxm7uA" target="_Ykmk8GOQEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YlA0o2OQEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YlA0pGOQEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YlA0oWOQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YlA0omOQEfGaD418Sxm7uA" points="[-1, 25, 73, -64]$[-1, 88, 73, -1]$[-60, 88, 14, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aMpg0GOQEfGaD418Sxm7uA" type="4001" element="_aMnEkGOQEfGaD418Sxm7uA" source="_eZ0r4GOQEfGaD418Sxm7uA" target="_Ykmk8GOQEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aMqH4GOQEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aMqH4WOQEfGaD418Sxm7uA" x="-31" y="13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aMpg0WOQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aMpg0mOQEfGaD418Sxm7uA" points="[-22, 13, -73, -68]$[-22, 81, -73, 0]$[36, 81, -15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aMyqwGOQEfGaD418Sxm7uA" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gWRxgmOQEfGaD418Sxm7uA" type="4001" element="_gWRKcGOQEfGaD418Sxm7uA" source="_3IMdsF-sEfGJm-VfRlIdsQ" target="_Jwok4GOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gWSYkGOQEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gWSYkWOQEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gWRxg2OQEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gWRxhGOQEfGaD418Sxm7uA" points="[60, -1, -407, 161]$[234, -1, -233, 161]$[234, -159, -233, 3]$[417, -159, -50, 3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PXk_QGOREfGaD418Sxm7uA" type="4001" element="_PXjxIGOREfGaD418Sxm7uA" source="_ULxY8GOPEfGaD418Sxm7uA" target="_gql_MGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_PXlmUGOREfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PXlmUWOREfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PXk_QWOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PXk_QmOREfGaD418Sxm7uA" points="[60, -1, -122, 151]$[178, -1, -4, 151]$[178, -135, -4, 17]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_bxC2UGOREfGaD418Sxm7uA" type="4001" element="_bxCPQGOREfGaD418Sxm7uA" source="_gql_MGOREfGaD418Sxm7uA" target="_ofHrcGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_bxC2U2OREfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_bxC2VGOREfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_bxC2UWOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_bxC2UmOREfGaD418Sxm7uA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sAzCcGOREfGaD418Sxm7uA" type="4001" element="_sAv_IGOREfGaD418Sxm7uA" source="_ofHrcGOREfGaD418Sxm7uA" target="_sAjx4GOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sAzCc2OREfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sAzCdGOREfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sAzCcWOREfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sAzCcmOREfGaD418Sxm7uA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BciyUGOSEfGaD418Sxm7uA" type="4001" element="_BcUI0GOSEfGaD418Sxm7uA" source="_ofHrcGOREfGaD418Sxm7uA" target="_B4-2sGOSEfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BcjZYGOSEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BcjZYWOSEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BciyUWOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BciyUmOSEfGaD418Sxm7uA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HBwHUGOSEfGaD418Sxm7uA" type="4001" element="_HBoLgGOSEfGaD418Sxm7uA" source="_B4-2sGOSEfGaD418Sxm7uA" target="_dCKf8GOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HBx8gGOSEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HBx8gWOSEfGaD418Sxm7uA" x="-23" y="-123"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HBwuYGOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HBwuYWOSEfGaD418Sxm7uA" points="[-43, -10, 416, -146]$[-302, -10, 157, -146]$[-302, 71, 157, -65]$[-459, 71, 0, -65]$[-459, 115, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HB6fYGOSEfGaD418Sxm7uA" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aLL2UGOSEfGaD418Sxm7uA" type="4001" element="_aLIzAGOSEfGaD418Sxm7uA" source="_KOgMoGOREfGaD418Sxm7uA" target="_gql_MGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aLO5oGOSEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aLO5oWOSEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aLL2UWOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aLL2UmOSEfGaD418Sxm7uA" points="[0, 4, -562, 558]$[558, 4, -4, 558]$[558, -537, -4, 17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aLTLEGOSEfGaD418Sxm7uA" id="(1.0,0.58)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_by7QMGOSEfGaD418Sxm7uA" type="4001" element="_by5bAGOSEfGaD418Sxm7uA" source="_Jwok4GOREfGaD418Sxm7uA" target="_gql_MGOREfGaD418Sxm7uA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_by8eUGOSEfGaD418Sxm7uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_by8eUWOSEfGaD418Sxm7uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_by7QMWOSEfGaD418Sxm7uA" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_by7QMmOSEfGaD418Sxm7uA" points="[0, -5, -687, 212]$[683, -5, -4, 212]$[683, -200, -4, 17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_by-6kGOSEfGaD418Sxm7uA" id="(1.0,0.58)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jwzbgGnOEfGG3LJZ6zip9w" type="4001" element="_jwDNkGnOEfGG3LJZ6zip9w" source="_B4-2sGOSEfGaD418Sxm7uA" target="_tostsGnOEfGG3LJZ6zip9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jw2e0GnOEfGG3LJZ6zip9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jw3s8GnOEfGG3LJZ6zip9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jw0CkGnOEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jw0CkWnOEfGG3LJZ6zip9w" points="[0, -8, 497, 39]$[73, -8, 570, 39]$[73, -103, 570, -56]$[-375, -103, 122, -56]$[-375, -48, 122, -1]$[-447, -48, 50, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jxCFAGnOEfGG3LJZ6zip9w" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2FdCIGnPEfGG3LJZ6zip9w" type="4001" element="_2FbM8GnPEfGG3LJZ6zip9w" source="_1ANRUGnPEfGG3LJZ6zip9w" target="_2halYGnPEfGG3LJZ6zip9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2Fe3UGnPEfGG3LJZ6zip9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2Fe3UWnPEfGG3LJZ6zip9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2FdpMGnPEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2FdpMWnPEfGG3LJZ6zip9w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4031wGnPEfGG3LJZ6zip9w" type="4001" element="_402noGnPEfGG3LJZ6zip9w" source="_2halYGnPEfGG3LJZ6zip9w" target="_6EQaAGnPEfGG3LJZ6zip9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_404c0GnPEfGG3LJZ6zip9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_404c0WnPEfGG3LJZ6zip9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4031wWnPEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4031wmnPEfGG3LJZ6zip9w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8WoFQGnPEfGG3LJZ6zip9w" type="4001" element="_8WjMwGnPEfGG3LJZ6zip9w" source="_6EQaAGnPEfGG3LJZ6zip9w" target="_tpzg8GnOEfGG3LJZ6zip9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8WpTYGnPEfGG3LJZ6zip9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8Wp6cGnPEfGG3LJZ6zip9w" y="-30"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8WosUGnPEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8WosUWnPEfGG3LJZ6zip9w" points="[-6, 1, -163, 5]$[158, 29, 1, 33]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8W1goGnPEfGG3LJZ6zip9w" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ED22sGnQEfGG3LJZ6zip9w" type="4001" element="_EDjUsGnQEfGG3LJZ6zip9w" source="_6EQaAGnPEfGG3LJZ6zip9w" target="_EDWgYGnQEfGG3LJZ6zip9w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ED3dwGnQEfGG3LJZ6zip9w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ED3dwWnQEfGG3LJZ6zip9w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ED22sWnQEfGG3LJZ6zip9w" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ED22smnQEfGG3LJZ6zip9w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
